# Part 3 of 4 — LUGAR clues (answers 37–54)
CLUES_PART3 = {
    "GRAND CANYON": [
        "Cânion profundo esculpe deserto no Arizona americano.",
        "Rio Colorado corre no fundo, milhares de metros abaixo do mirante.",
        "Parque nacional recebe milhão de visitante por ano.",
        "Camada de rocha expõe história geológica em faixa colorida.",
        "Mule ride desce trilha íngreme até o rio.",
        "Helicóptero turístico sobrevoa abismo com vento forte.",
        "South Rim abre o ano todo com loja e trilha pavimentada.",
        "Nascer do sol pinta parede vermelha no Mather Point.",
        "Skywalk de vidro no lado oeste assusta quem tem vertigem.",
        "Indígena Hualapai opera parte do turismo na borda oeste.",
        "Inverno traz neve rara na borda sul.",
        "Largura chega a dezenas de quilômetros de um lado ao outro.",
        "John Wesley Powell explorou rio em barco no século XIX.",
        "Trilha Bright Angel exige reserva e garrafa grande.",
        "Filme western usou paisagem como pano de fundo.",
        "Nome Grand fala de escala, não de rio específico.",
        "Quem encosta no parapece sente vento seco puxar o chapéu.",
    ],
    "EVEREST": [
        "Pico mais alto da Terra fica na cordilheira do Himalaia.",
        "Fronteira Nepal e China divide meu cume.",
        "Oito mil e oitocentos metros arredondados no topo.",
        "Sherpa guia expedição e carrega oxigênio extra.",
        "Campo base recebe tenda de montanhista na primavera.",
        "Edmund Hillary e Tenzing Norgay chegaram primeiro em 1953.",
        "Fila de escalador no cume virou imagem polêmica recente.",
        "Avalanche e tempestade matam quem sube desprevenido.",
        "Nome local Sagarmatha ou Chomolungma depende do idioma.",
        "Oxigênio em cilindro facilita, mas não garante volta.",
        "Corpo congelado ainda marca rota conhecida na subida.",
        "Permissão cara e lixo acumulado geram debate ambiental.",
        "Jet stream bate no topo com vento de furacão.",
        "Base camp trek é trilha popular sem chegar ao cume.",
        "Geologia levantou rocha marinha até altura absurda.",
        "Filme e documentário mostram frostbite e dedo perdido.",
        "Quem chega no topo fica minutos antes de descer por falta de ar.",
    ],
    "DESERTO DO SAARA": [
        "Areia e dunas cobrem norte da África em escala continental.",
        "Camelo de uma ou duas corcovas atravessa rota comercial antiga.",
        "Oásis de palmeira interrompe mar de calor seco.",
        "Temperatura de dia e noite varia dezenas de graus.",
        "Caravana histórica ligou Mediterrâneo a Sahel.",
        "Países como Marrocos, Argélia e Egito me tocam.",
        "Duna Erg Chebbi e outras formam onda de areia laranja.",
        "Vento constante remodela borda da duna.",
        "Escorpião e cobra sobrevivem escondidos de dia.",
        "Filme Lawrence da Arábia usou paisagem parecida.",
        "Expansão recente avança sobre pasto ao sul, preocupa climatólogo.",
        "Turista dorme em tenda berbere e come tagine.",
        "Céu noturno sem poluição revela Via Láctea inteira.",
        "Petróleo e gás ficaram debaixo de parte do leito.",
        "Nome árabe significa deserto, redundante em tradução literal.",
        "Chuva rara transforma wadi em rio efêmero.",
        "Quem caminha ao meio-dia sente sol queimar sola mesmo com sandália.",
    ],
    "ANTÁRTIDA": [
        "Continente gelado no polo sul, sem população fixa.",
        "Estação científica de vários países opera no verão austral.",
        "Pinguim-imperador e foca-leopardo aparecem na costa.",
        "Placa de gelo do tamanho de país às vezes se desprende.",
        "Tratado internacional proíbe mineração e militarização.",
        "Temperatura negativa extrema impede árvore nativa.",
        "Aurora austral brilha no céu escuro do inverno polar.",
        "Barco de expedição cruza Drake Passage com mar revolto.",
        "Pesquisador estuda clima e camada de ozônio aqui.",
        "Bandeira de consulta pendurada em base, não governo único.",
        "Iceberg flutuante deriva até ameaçar rota de navio.",
        "Voo charter pousa em pista de gelo compactado.",
        "Sol de meia-noite ocorre no verão do hemisfério sul.",
        "Fossil de dinossauro provou clima quente no passado remoto.",
        "Turismo paga caro por day trip de barco ou avião.",
        "Brasil mantém base com nome de meteorologista na região.",
        "Quem desce do zodiac sente vento cortar face mesmo com casaco grosso.",
    ],
    "NOVA YORK": [
        "Arranha-céu define ilha densa entre rios Hudson e East.",
        "Times Square pisca anúncio e recebe virada de ano global.",
        "Estátua da Liberdade fica no porto ao sul da ilha.",
        "Central Park quebra concreto no meio de Manhattan.",
        "Broadway vende musical caro e fila na bilheteria.",
        "Metrô 24 horas cheira a trilho e carrega oito milhões de morador.",
        "Brooklyn Bridge liga bairro hipster à ilha principal.",
        "Pizza de fatia fina e bagel com cream cheese alimentam correria.",
        "Empire State e One World Trade disputam foto de turista.",
        "Inverno traz neve que vira poça cinza em dois dias.",
        "ONU reúne delegação no East Side.",
        "Wall Street concentra bolsa e terno apressado.",
        "Harlem guarda história de jazz e migração afro-americana.",
        "Yellow cab ainda aparece, embora app tenha tomado corrida.",
        "Five boroughs formam cidade: Bronx, Queens, Brooklyn, Staten, Manhattan.",
        "Filme americano usa minha skyline como plano genérico de metrópole.",
        "Quem sobe observatório olha grid de avenida numérica até o horizonte.",
    ],
    "PARIS": [
        "Capital francesa beija rio Sena com ponte de arco.",
        "Torre de ferro treliçado virou símbolo nacional.",
        "Louvre abriga Mona Lisa atrás de vidro e multidão.",
        "Baguete sai de padaria com croissant na vitrine.",
        "Metrô art nouveau entra em estação com azulejo.",
        "Notre-Dame reconstrói telhado após incêndio de 2019.",
        "Champs-Élysées liga arco ao obelisco na praça.",
        "Bicicleta Vélib' divide calçada com café ao ar livre.",
        "Eiffel brilha à noite; Seine recebe barco jantar.",
        "Bairro Montmartre sobe ladeira com Sacré-Cœur branco.",
        "Moda e perfumaria vendem luxo na avenida.",
        "Guerra e revolução marcaram praça da Concorde e Bastilha.",
        "Turista fila no Louvre, esquece museu menor ao lado.",
        "Inverno pede casaco; verão lota picnic no Jardin du Luxembourg.",
        "Françês reclama de turista, mas economia depende dele.",
        "Arco do Triunfo homenageia exército napoleônico.",
        "Quem pede café pede expresso em xícara pequena, não jarra americana.",
    ],
    "LONDRES": [
        "Thames serpenteia capital britânica com ponte basculante.",
        "Big Ben e Parlamento ficam em Westminster.",
        "Metrô mais antigo do mundo corre abaixo do asfalto.",
        "Palácio de Buckingham troca guarda com uniforme vermelho.",
        "Chuva fina e persistente molha casaco o ano inteiro.",
        "Museu British guarda artefato colonial controverso.",
        "Tower Bridge levanta passagem para navio alto.",
        "Double-decker bus vermelho ainda cruza Piccadilly.",
        "Pub vende ale amarga e fish and chips na sexta.",
        "Hyde Park recebe concerto e protesto de domingo.",
        "Cabine telefônica vermelha virou selfie de turista.",
        "Teatro West End rivaliza Broadway em musical.",
        "Fuso horário GMT nasceu da observatório em Greenwich.",
        "Multiculturalismo transformou bairro em curry e kebab.",
        "Brexit mudou documento de europeu que veio morar.",
        "London Eye gira cápsula lenta sobre rio.",
        "Quem desce na Piccadilly Circus vê neon e multidão cruzando.",
    ],
    "TÓQUIO": [
        "Metrópole japonesa mistura templo xintoísta e prédio neon.",
        "Cruzamento de Shibuya para multidão em faixa zebrada.",
        "Monte Fuji aparece no horizonte em dia limpo de inverno.",
        "Metrô punctual empurra passageiro em hora de pico.",
        "Sushi de esteira e ramen de balcão alimentam trabalhador.",
        "Imperador reside no Palácio cercado de jardim central.",
        "Akihabara vende eletrônico e cultura otaku.",
        "Terremoto e typhoon entram no plano de evacuação escolar.",
        "Torre vermelha e branca copia torre parisiense em escala local.",
        "Cherry blossom na primavera lota parque com picnic.",
        "Sumô, kabuki e anime exportam imagem cultural.",
        "Disney resort fica na periferia com fila de domingo.",
        "Onsen day trip alivia estresse fora do centro.",
        "Kanji e hiragana cobrem placa que turista não lê.",
        "População urbana passa de dezena de milhões na região.",
        "Tsukiji outer market vende peixe cru cedo demais pro estômago fraco.",
        "Quem entra no metrô guarda silêncio e celular no bolso.",
    ],
    "ROMA": [
        "Capital italiana espalha ruína imperial no meio do trânsito.",
        "Coliseu recebe fila de turista sob sol de julho.",
        "Fontana di Trevi recebe moeda jogada de costas.",
        "Vaticano funciona como estado dentro da minha cidade.",
        "Espaguete alla carbonara e gelato vendem-se a cada esquina.",
        "Fórum Romano guarda coluna caída e arco triunfal.",
        "Scooter vespa desvia entre carro estacionado ilegal.",
        "Panteão mantém cúpula de concreto romano intacta.",
        "Papa aparece na varanda da praça San Pietro.",
        "Metro linha A para perto do Vaticano e do Coliseu.",
        "Imperadores expandiram império a partir daqui.",
        "Trastevere concentra restaurante e bar à noite.",
        "Sapatilha confortável é item obrigatório pro calçamento irregular.",
        "Filme La Dolce Vita immortalizou fonte e scooter.",
        "Catacumba cristã fica abaixo de bairro periférico.",
        "Sete colinas originaram mito de fundação com Romulus.",
        "Quem lança moeda na fonte promete voltar, diz a tradição.",
    ],
    "EGITO": [
        "País africano beijado pelo Nilo do sul ao delta.",
        "Pirâmide de Gizé fica perto da capital Cairo.",
        "Esfinx e vale dos reis concentram turismo faraônico.",
        "Hieroglifo cobriu templo antes da pedra de Rosetta.",
        "Deserto do Saara ocupa maior parte do território.",
        "Mar Vermelho oferece mergulho em resort de Sharm.",
        "Revolução de 2011 derrubou presidente na praça Tahrir.",
        "Muçulmano majoritário ouve chamada da mesquita ao amanhecer.",
        "Papyrus vendido em loja turística imita rolo antigo.",
        "Aswan e Luxor guardam templo de Karnak e Abu Simbel.",
        "Economia depende de canal de Suez e turismo.",
        "Ful e taameya alimentam rua no café da manhã.",
        "Calor seco do verão passa de quarenta graus fácil.",
        "Múmia exposta em museu gera debate ético.",
        "Bandeira trinca águia, vermelho, branco e preto.",
        "Árabe é idioma oficial; inglês aparece em hotel.",
        "Quem desce ao túmulo na vale sente ar úmido e escuro.",
    ],
    "JAPÃO": [
        "Arquipélago asiático de quatro ilhas principais no Pacífico.",
        "Monte Fuji é cone nevado que aparece em cartão postal.",
        "Tóquio concentra governo, empresa e metrô lotado.",
        "Terremoto frequente moldou prédio flexível e treino escolar.",
        "Sushi, sashimi e matcha exportam gastronomia.",
        "Imperador simbólico habita palácio na capital.",
        "Shinkansen liga cidade em trem-bala silencioso.",
        "Hiroshima e Nagasaki carregam memória nuclear.",
        "Queda das cerejeiras na primavera vira feriado picnic.",
        "Anime e mangá influenciam adolescente do mundo inteiro.",
        "Trabalho longo e cortesia extrema definem etiqueta urbana.",
        "Kyoto guarda templo de madeira e gueixa tradicional.",
        "Ilha Hokkaido traz neve e ski no inverno.",
        "População envelhece; robô cuida de idoso em teste.",
        "Bandeira branca com sol vermelho discóide.",
        "Onsen exige regra de nudez comunitária na água quente.",
        "Quem entra em casa tira sapato e fala sumimasen o tempo todo.",
    ],
    "ARGENTINA": [
        "País sul-americano em forma de triângulo longo.",
        "Buenos Aires respira tango na San Telmo de domingo.",
        "Gauchos pastoreiam no pampa plano ao sul.",
        "Cordilheira dos Andes divide fronteira com Chile.",
        "Glaciar Perito Moreno quebra parede de gelo na Patagônia.",
        "Messi e Maradona viraram ídolo de futebol mundial.",
        "Asado com chimichurri alimenta churrasco de fim de semana.",
        "Peso argentino oscila; dólar blue aparece na conversa.",
        "Malbec de Mendoza enche taça exportada.",
        "Ushuaia se vende como cidade do fim do mundo.",
        "Evita Perón entrou na história e no musical.",
        "Iguazu compartilha catarata com Brasil vizinho.",
        "Mate com bombilla passa de mão em grupo.",
        "Inflação alta aparece na manchete todo mês.",
        "Bandeira celeste e branca traz sol de maio.",
        "Espanhol local distorce pronúncia do ye em sh.",
        "Quem pede empanada come massa recheada quente na calle.",
    ],
    "PORTUGAL": [
        "País ibérico no canto oeste da Europa.",
        "Lisboa sobe ladeira de eléctrico amarelo rangente.",
        "Porto vende vinho doce com nome da cidade.",
        "Explorador partiu daqui no século XV rumo ao Atlântico.",
        "Fado canta saudade em restaurante com guitarra.",
        "Pastel de nata com canela vende-se quente na Belém.",
        "Algarve recebe britânico de férias na praia.",
        "Azulejo azul cobre parede de igreja e estação.",
        "Cristiano Ronaldo exportou orgulho da ilha da Madeira.",
        "Euro substituiu escudo antes do milênio.",
        "Pontes sobre o Tejo ligam margem nova e antiga.",
        "Sardinha assada vira cheiro de festival de junho.",
        "Braga e Coimbra guardam universidade e igreja barroca.",
        "Turista confunde português europeu com brasileiro na pronúncia.",
        "Sintra concentra palácio colorido em serra úmida.",
        "Bandeira verde e vermelha traz brasão armilar.",
        "Quem pede bica toma café curto forte no balcão.",
    ],
    "MARTE": [
        "Planeta vermelho orbita sol mais afastado que a Terra.",
        "Dia dura pouco mais de vinte e quatro horas terrestres.",
        "Monte Olympus é vulcão gigante no meu hemisfério.",
        "Rover da NASA fotografou solo rochoso e seco.",
        "Atmosfera fina de CO2 não sustenta respiração humana.",
        "Elon Musk promete colonização em discurso otimista.",
        "Canal marciano virou mito antes da sonda close-up.",
        "Dois satélites pequenos, Phobos e Deimos, me circundam.",
        "Polo sul guarda gelo de água sob capa de poeira.",
        "Gravidade fraca deixa astronauta pular mais alto.",
        "Tempestade global de poeira cobre superfície por meses.",
        "Filme The Martian plantou batata fictícia na ficção.",
        "Cor avermelhada vem de óxido de ferro na areia.",
        "Sinal de rádio atrasa minutos por distância ao Earth.",
        "Exoplaneta não sou; vizinho interno do cinturão.",
        "China e EUA competem por pouso suave recente.",
        "Quem olha no telescópio amador vê disco laranja pequeno.",
    ],
    "LUA": [
        "Satélite natural da Terra ilumina noite sem luz própria.",
        "Neil Armstrong pisou poeira cinza em 1969.",
        "Fase nova a cheia muda forma visível a cada semana.",
        "Maré oceânica sobe e desce puxada pela minha gravidade.",
        "Superfície craterada guarda registro de impacto antigo.",
        "Apollo deixou bandeira e pegada controversa em foto.",
        "Eclipse solar acontece quando me posiciono na frente do sol.",
        "Lado oculto ficou invisível da Terra até sonda soviética.",
        "Poeta romântico comparou rosto humano ao meu disco.",
        "Noite de lua cheia ilumina trilha sem lanterna.",
        "NASA planeja retorno habitado décadas depois do último pouso.",
        "Gravidade baixa permite salto lento em traje espacial.",
        "Rocha trazida em missão ainda estuda laboratório.",
        "Calendário lunar marca feriado em cultura islâmica e asiática.",
        "Lobo uivando é clichê de filme de terror.",
        "Distância média de trezentos e oitenta e mil quilômetros da Terra.",
        "Quem observa com binóculo vê monte e mar escuro sem atmosfera.",
    ],
    "DISNEYLAND": [
        "Parque temático na Califórnia inaugurado por Walt em 1955.",
        "Castelo de conto de fada marca entrada da Main Street.",
        "Mickey Mouse cumprimenta criança na fila de autógrafo.",
        "Pirates of the Caribbean virou filme depois do ride.",
        "Space Mountain escurece trilho indoor de montanha-russa.",
        "Ingresso caro e fila longa testam paciência de pai.",
        "Fogos no castelo fecham noite com projeção mapeada.",
        "Personagem fantasiado não pode quebrar personagem na foto.",
        "FastPass ou Genie+ vende fila mais curta digital.",
        "Churros e pipoca doce alimentam família o dia todo.",
        "Expansão em Orlando copiou ideia com parque maior.",
        "Star Wars Galaxy's Edge vende sabre de luz caro.",
        "Parade diurno passa com carro alegórico e música.",
        "Funcionário se chama cast member, não empregado comum.",
        "Anaheim recebe turista de avião no sul da Califórnia.",
        "Ratatouille ride chegou depois de décadas de clássico.",
        "Quem encontra Mickey no fim do dia leva cansaço e foto borrada.",
    ],
    "HOGWARTS": [
        "Castelo escocês fictício abriga escola de magia britânica.",
        "Harry Potter aprendeu feitiço e voo de vassoura aqui.",
        "Grifinória, Sonserina, Corvinal e Lufa-Lufa dividem casa.",
        "Trem escolar vermelho parte da plataforma nove e meia.",
        "Dumbledore dirige como diretor sábio e enigmático.",
        "Quadro se move e escada muda de lugar sozinha.",
        "Snape ensina poção no porão úmido.",
        "Quadribol disputa ponto com snitch dourada voadora.",
        "Bolo de festa aparece quando aniversariante acorda.",
        "JK Rowling inventou regra e mapa do mundo bruxo.",
        "Filme usou castelo real e estúdio para corredor.",
        "Voldemort assombra como antagonista sem nariz.",
        "Varinha escolhe bruxo, não o contrário, diz a loja.",
        "Criatura como hippogriff e basilisco entram na trama.",
        "Sala precisa aparece só pra quem realmente precisa.",
        "Turista visita estúdio Leavesden fora de Londres pra ver cenário.",
        "Quem espera carta de admissão ainda olha coruja no telhado.",
    ],
    "NÁRNIA": [
        "Mundo fictício atrás do guarda-roupa na obra de C.S. Lewis.",
        "Leão Aslam fala e representa figura cristã alegórica.",
        "Feiticeira branca deixa inverno eterno sem Natal.",
        "Armário de madeira liga Inglaterra à floresta nevada.",
        "Irmãos Pevensie viram realeza na saga infantil.",
        "Fauno Tumnus toca flauta na neve da primeira visita.",
        "Cair Paravel é castelo costeiro de reino felino.",
        "Cronologia interna corre mais rápida que Terra externa.",
        "Série de sete livros fechou com último volume apocalíptico.",
        "Disney adaptou filme com leão CGI e criança atriz.",
        "Centauro e dryad populam floresta mágica.",
        "Profeta e profecia guiam escolha de monarca criança.",
        "Teletransporte por anel ou pintura aparece em volume posterior.",
        "Tema de redenção e sacrifício permeia narrativa cristã.",
        "Guarda-roupa vazio na parede vira portal só na primeira vez.",
        "Turista não compra passagem; leitor imagina do quarto.",
        "Quem entra na neve sente casaco inglês ficar fino demais.",
    ],
}
