# Part 1 of 4 — LUGAR clues (answers 1–18)
CLUES_PART1 = {
    "CRISTO REDENTOR": [
        "De longe, carioca me enxerga no horizonte antes do por do sol.",
        "Vento no topo do morro quase derruba chapéu de quem chega.",
        "Turista escolhe entre trem histórico, van ou trilha pra subir.",
        "Luzes noturnas me deixam visível da orla inteira.",
        "Estilo Art Déco, não sou catedral medieval.",
        "Projeto misturou engenheiro carioca e escultor francês nos anos 1920.",
        "Fico dentro do Parque Nacional da Tijuca.",
        "Braços abertos medem dezenas de metros de ponta a ponta.",
        "Inaugurado em outubro de 1931, com festa enorme.",
        "Concreto armado e pedra-sabão me sustentam no Corcovado.",
        "Altura passa de trinta metros só na figura, pedestal soma mais.",
        "Entrei na votação das Sete Maravilhas do Mundo Moderno.",
        "Raio já quebrou pedacinho da minha mão direita.",
        "Domingo de manhã o ponto fica lotado de fila.",
        "Represento figura central do cristianismo num gesto de abraço.",
        "Cartão postal do Rio quase sempre me inclui de fundo.",
        "Meu sobrenome fala em quem salva, não em doce de mesa.",
    ],
    "PÃO DE AÇÚCAR": [
        "Formato arredondado lembra doce cristalizado que deu meu nome.",
        "Fico entre Baía de Guanabara e mar aberto.",
        "Bondinho em duas paradas sobe até meu topo.",
        "Granito e gnaisse me formaram há milhões de anos.",
        "Urca é o bairro que me abraça na base.",
        "Praia Vermelha fica colada nos meus pés.",
        "Do alto, Copacabana e Niterói cabem numa foto só.",
        "Primeiro teleférico abriu em 1912, turista vem desde então.",
        "Morro íngreme, trilha de escalada atrai aventureiro.",
        "Pôr do sol aqui vira programa de casal carioca.",
        "Apareço em novela quando a cena precisa de vista icônica.",
        "Dois bondinhos cruzam no meio do caminho, um sobe e outro desce.",
        "Nome popular veio da semelhança com refino de cana.",
        "Guia costuma apontar o Morro da Urca no meio do percurso.",
        "Helicóptero turístico rodeia meu contorno o dia inteiro.",
        "Sou monólito, não sou vulcão ativo.",
        "Quem desce do bondinho fala que o Rio parece maquete.",
    ],
    "CATARATAS DO IGUAÇU": [
        "Fronteira divide minha vista entre Brasil e Argentina.",
        "Parque Nacional protege minha área de quedas.",
        "Garganta do Diabo concentra o barulho mais assustador.",
        "Foz do Iguaçu é a cidade base pro visitante.",
        "UNESCO listou meu conjunto como Patrimônio Mundial.",
        "Na cheia, o Iguaçu joga água demais pra contar.",
        "Passeio de barco encosta na névoa e molha todo mundo.",
        "Passarela de metal leva pé bem perto da queda.",
        "Mata Atlântica e fauna rodeiam os mirantes.",
        "Helicóptero sobrevoa o arco de quedas em forma de ferradura.",
        "Lado argentino tem trilha longa entre várias cascatas menores.",
        "Macuco Safari é nome de um dos passeios molhados.",
        "Paraná abriga meu lado brasileiro oficial.",
        "Turista grava vídeo com som de trovão constante.",
        "Tríplice fronteira inclui Paraguai perto d'água.",
        "Aves coloridas aparecem nos gramados do parque.",
        "Quem visita fala que a névoa pinta arco-íris no ar.",
    ],
    "PANTANAL": [
        "Cheia e seca mudam minha paisagem de um ano pro outro.",
        "Jacaré aparece quieto na beira da estrada de terra.",
        "Onça-pintada é troféu de quem faz safári fotográfico aqui.",
        "Mato Grosso e Mato Grosso do Sul dividem meu território.",
        "Maior planície alagável do planeta, dizem os mapas.",
        "UNESCO me reconheceu como Patrimônio Natural.",
        "Na aula de geografia me classificam como planície alagável tropical.",
        "Pesca esportiva e observação de aves movem a economia local.",
        "Fazenda pantaneira recebe hóspede com churrasco e barco.",
        "Tuiuiú e arara vermelha estampam folder turístico.",
        "Estrada Transpantaneira corta alagado em época de chuva.",
        "Centro-Oeste concentra minha fama de vida selvagem.",
        "Seca deixa lagoa rasa virar pasto de gado.",
        "Documentário de natureza adora filmar meu pôr do sol.",
        "Cuiabá e Campo Grande são portas de entrada comuns.",
        "Capivara vira figura coadjuvante em quase todo passeio.",
        "Quem vem uma vez costuma voltar na outra estação.",
    ],
    "LENÇÓIS MARANHENSES": [
        "Dunas brancas parecem lençol estendido no chão.",
        "Lagoas de água doce enchem depois da chuva no Nordeste.",
        "Barreirinhas é cidade que organiza a visita pra maioria.",
        "Maranhão me abriga como parque nacional.",
        "Areia fina queima pé descalço ao meio-dia.",
        "Lagoa Azul e Lagoa Bonita disputam foto mais bonita.",
        "Vento remodela minhas dunas a cada temporada.",
        "Pareço deserto, mas chove o suficiente pra encher lagoa.",
        "Trilha sem guia local é receita pra se perder.",
        "Drone mostra contraste azul-turquesa com branco da areia.",
        "4x4 leva turista até trechos mais famosos.",
        "Vegetação rala sobrevive só nas bordas úmidas.",
        "Documentário de TV Globo já exibiu minhas imagens de cima.",
        "Atins e Santo Amaro também servem de base.",
        "Calor forte pede chapéu, protetor e muita água.",
        "Nome evoca tecido secando no terreiro.",
        "Quem mergulha na lagoa fala que a água é morna e rasa.",
    ],
    "FERNANDO DE NORONHA": [
        "Arquipélago fica longe do continente, no Atlântico.",
        "Pernambuco me administra no mapa político.",
        "Taxa de preservação ambiental cobra todo visitante.",
        "Número de turistas por dia tem teto rígido.",
        "Baía do Sancho aparece em ranking de praia do mundo.",
        "Golfinho-rotador salta perto da Praia do Sancho de manhã.",
        "Mergulho com cilindro ou snorkel é programa clássico.",
        "UNESCO protegeu minhas ilhas como Patrimônio Natural.",
        "Ilha principal concentra pousada, bar e pista de avião.",
        "História inclui presídio e presença militar.",
        "Água transparente deixa peixe visível sem máscara.",
        "Proibido plástico descartável em várias áreas.",
        "Voo partindo de Recife ou Natal é caminho usual.",
        "Tartaruga marinha desova em época certa do ano.",
        "Preço alto afasta quem busca destino barato.",
        "Morro Dois Irmãos vira cartão postal do arquipélago.",
        "Quem pisa aqui jura que o mar parece piscina infinita.",
    ],
    "RIO DE JANEIRO": [
        "Cidade Maravilhosa é apelido que colou no meu nome.",
        "Montanha e mar dividem o mesmo endereço urbano.",
        "Fui capital federal por quase dois séculos.",
        "Carnaval de rua e desfile no Sambódromo me definem.",
        "Maracanã guarda história de final de Copa.",
        "Copacabana e Ipanema estão na minha orla.",
        "Bondinho sobe morro com vista de baía.",
        "Estátua de braços abertos domina skyline do Corcovado.",
        "Réveillon na areia junta milhão de gente.",
        "Estado homônimo me tem como capital.",
        "Sudeste brasileiro é minha região no IBGE.",
        "Cristo no alto virou símbolo exportado pro exterior.",
        "Novela da Globo adora usar meu cenário.",
        "Lagoa Rodrigo de Freitas fica entre morro e mar.",
        "Metro e BRT tentam aguentar trânsito de turista.",
        "Bossa nova nasceu em bairro meu com vista pro mar.",
        "Quem visita fala que o pôr do sol na Urca não tem preço.",
    ],
    "SÃO PAULO": [
        "Maior metrópole do Brasil, trânsito nunca dorme.",
        "Paulistano corre atrás de metrô, café e reunião.",
        "Avenida Paulista concentra banco, museu e manifestação.",
        "Mercado Municipal vende mortadela gigante no centro.",
        "Mistura de imigrante italiano, japonês e nordestino me formou.",
        "Edifício Martinelli já foi prédio mais alto da América Latina.",
        "Parque Ibirapuera recebe corrida de domingo e evento.",
        "Campeonato paulista de futebol divide torcida entre três gigantes.",
        "Congonhas e Guarulhos pousam avião o tempo todo.",
        "Chuva de tarde surpreende quem saiu sem guarda-chuva.",
        "Museu do Futebol fica dentro do estádio do Pacaembu.",
        "Serra do Mar escora meu limite leste.",
        "Pinacoteca e MASP disputam fila de domingo.",
        "Gastronomia vai de feijoada em boteco a restaurante estrelado.",
        "Crime e desigualdade aparecem na manchete todo dia.",
        "Capital do estado que mais puxa PIB nacional.",
        "Quem mora aqui diz que só se entende depois de se perder no centro.",
    ],
    "SALVADOR": [
        "Pelourinho colorido sobe ladeira no centro histórico.",
        "Baía de Todos os Santos abraça meu porto.",
        "Capital da Bahia, berço de cultura afro-brasileira.",
        "Carnaval aqui mexe trio elétrico na orla.",
        "Elevador Lacerda liga Cidade Alta e Cidade Baixa.",
        "Acarajé na rua é lanche obrigatório pro visitante.",
        "Farol da Barra marca fim de tarde na orla.",
        "Igreja de São Francisco ostenta ouro por dentro.",
        "Axé e samba-reggae saem de bloco o ano inteiro.",
        "Primeira capital do Brasil colonial, história pesada.",
        "Pelé jogou aqui antes de virar lenda nacional.",
        "Verão traz turista europeu pra praia de Porto da Barra.",
        "Chuva forte alaga avenida em minutos no outono.",
        "Nome completo da cidade homenageia santo navigator.",
        "Mercado Modelo vende artesanato perto do cais.",
        "Terreiro de candomblé e igreja católica dividem o mesmo bairro.",
        "Quem dança na rua durante o Carnaval sente o tambor no peito.",
    ],
    "BRASÍLIA": [
        "Capital federal planejada no Planalto Central.",
        "Oscar Niemeyer desenhou prédios curvos por aqui.",
        "Eixo Monumental corta a cidade como régua.",
        "Congresso, Palácio do Planalto e Supremo formam minha praça.",
        "Inaugurada em 1960, cidade jovem demais pro Brasil.",
        "Distrito Federal me abriga, não sou estado comum.",
        "Lago Paranoá recebe lancha e pedal no fim de semana.",
        "Asa Sul e Asa Norte dividem moradia em blocos numerados.",
        "Catedral de vidro parece coroa aberta pro céu.",
        "Seca do cerrado deixa ar rarefeito no inverno.",
        "Torre de TV oferece vista de planta urbana inteira.",
        "JK foi o presidente que enfiou capital no meio do país.",
        "Churrascaria e rodízio alimentam servidor público e turista.",
        "Placa de carro azul com DF denuncia morador local.",
        "Setor de autarquias concentra ministério e repartição.",
        "Cidade sem esquina tradicional, tudo feito pra carro.",
        "Visitante estrangeiro estranha minha falta de calçada longa.",
    ],
    "RECIFE": [
        "Venho das pontes sobre rios que cortam o centro.",
        "Capital de Pernambuco, litoral nordestino.",
        "Marco Zero guarda azulejo e vista pro porto.",
        "Frevo e maracatu animam Carnaval na rua.",
        "Praia de Boa Viagem fica na zona sul da cidade.",
        "Olinda vizinha sobe ladeira com igreja barroca.",
        "Cidade também me chamam de Veneza Brasileira.",
        "Galo da Madrugada reúne multidão no sábado de Carnaval.",
        "Ponte Maurício de Nassau liga bairros sobre capibaribe.",
        "Culinária local pede bolo de rolo e caldinho de sururu.",
        "Porto Digital virou polo de tecnologia no antigo cais.",
        "Chuva rápida alaga avenida e para o trânsito.",
        "Aeroporto dos Guararapes recebe voo do Sudeste o dia todo.",
        "Praia urbano tem aviso de tubarão em alguns trechos.",
        "Rua do Bom Jesus guarda sinagoga histórica.",
        "Museu Cais do Sertão homenageia Luiz Gonzaga.",
        "Quem pisa no Marco Zero sente brisa salgada do cais.",
    ],
    "CURITIBA": [
        "Capital paranaense, frio surpreende quem vem do Nordeste.",
        "Jardim Botânico tem estufa de vidro postada no gramado.",
        "BRT e tubo de ônibus viraram modelo copiado no país.",
        "Parque Barigui recebe capivara perto da pista de corrida.",
        "Planejamento urbano me colocou em ranking de qualidade de vida.",
        "Feira do Largo da Ordem anima domingo no centro.",
        "Pinhão aparece em doce típico de festa junina.",
        "Serra do Mar fica a uma hora de carro descendo pro litoral.",
        "Teatro Guaíra e Ópera de Arame dividem palco cultural.",
        "Inverno traz casaco em julho, mesmo sem neve.",
        "Rua das Flores é calçadão com banco e café.",
        "Memorial no centro guarda exposição sobre imigração europeia.",
        "Estação ferroviária antiga abriga loja e restaurante.",
        "Bairro italiano de Santa Felicidade serve rodízio de massa.",
        "Lago da Ópera reflete arame curvado ao entardecer.",
        "Muita gente me chama de capital ecológica por causa das praças.",
        "Morador usa agasalho leve o ano inteiro, não exagera no calor.",
    ],
    "MANAUS": [
        "Encontro das Águas junta rio escuro e claro sem misturar na hora.",
        "Capital amazonense, porta de entrada da floresta.",
        "Teatro Amazonas abre temporada de ópera no meio da selva.",
        "Zona Franca atrai indústria pela isenção fiscal.",
        "Calor úmido cola camisa no corpo o ano todo.",
        "Barco hotel sobe rio Negro até comunidade ribeirinha.",
        "Copa de 2014 trouxe arena nova pra minha orla.",
        "Peixe tambaqui e tacacá aparecem no prato local.",
        "Floresta Amazônica começa nos arredores da cidade.",
        "Pontes sobre o Negro ligam margens distantes.",
        "Biodiversidade do entorno vira argumento de ecoturismo.",
        "Rubber boom no século XIX deixou palácio e mansão no centro.",
        "Chuva de tarde cai forte e para em uma hora.",
        "Voo do Sudeste pousa no Eduardo Gomes o dia inteiro.",
        "Guia mostra boto cor-de-rosa em passeio de barco.",
        "Fico longe do oceano, mas movimento de barco no porto fluvial é grande.",
        "Quem entra no teatro de gala sente Europa no meio da mata.",
    ],
    "FLORIANÓPOLIS": [
        "Ilha e continente ligados por ponte Hercílio Luz.",
        "Capital de Santa Catarina, apelidada de Magic Island.",
        "Praia de Jurerê recebe turista argentino no verão.",
        "Lagoa da Conceição concentra bar, windsurf e trilha.",
        "Centro histórico guarda casario açoriano.",
        "Santo Antônio de Lisboa serve ostras no fim de tarde.",
        "Surfe em Joaquina atrai campeonato e mochileiro.",
        "Morro da Cruz oferece vista 360 da baía.",
        "Universidade Federal lota aluguel temporada de janeiro.",
        "Chuva de verão interrompe churrasco na laje.",
        "Mercado Público vende sequência de petisco e cerveja.",
        "Praia Mole e Campeche disputam onda e natureza.",
        "Aeroporto internacional recebe voo de São Paulo e Chile.",
        "Ilha do Campeche pede autorização pra desembarcar.",
        "Castelo de chocolate na região vira programa de família.",
        "Galeteria e porção de batata alimentam mesa de amigo.",
        "Morador da ilha briga com trânsito de janeiro e agradece o outono.",
    ],
    "OURO PRETO": [
        "Casario barroco sobe ladeira em Minas Gerais.",
        "Universidade Federal ocupa convento antigo no centro.",
        "Igreja de São Francisco de Assis guarda Aleijadinho na fachada.",
        "Mineração de ouro no século XVIII me fundou.",
        "Carnaval de rua aqui mistura estudante e batucada.",
        "Cidade virou Patrimônio Mundial da UNESCO.",
        "Pedra no calçamento exige sapato confortável pro turista.",
        "Museu da Inconfidência conta história de Tiradentes.",
        "Nevoeiro de manhã esconde telhado de lha.",
        "Trem turístico liga Mariana nos fins de semana.",
        "Sem semáforo no centro histórico, carro divide rua estreita.",
        "Escola de Minas formou engenheiro desde o Império.",
        "Igreja do Pilar ostenta ouro por dentro.",
        "Feira de pedra-sabão vende artesanato na praça.",
        "Nome antigo Vila Rica virou referência em livro de história.",
        "Barragem de rejeito em Mariana afetou rio da região em 2015.",
        "Quem sobe a ladeira da Igreja de São Francisco ofega antes da foto.",
    ],
    "MARACANÃ": [
        "Estádio carioca já recebeu final de Copa do Mundo.",
        "Nome oficial lembra rio que passava perto do terreno.",
        "Capacidade passou de duzentos mil espectadores na era antiga.",
        "Flamengo, Fluminense, Botafogo e Vasco jogam clássico aqui.",
        "Pelé marcou gol número mil neste gramado.",
        "Reforma para 2014 trouxe cobertura e assento individual.",
        "Show de rock e missa do Papa também lotaram arquibancada.",
        "Metrô desce na estação com meu nome na Zona Norte.",
        "Torcida cantando na arquibancada faz tremer o concreto.",
        "Museu dentro do estádio guarda camisa e troféu histórico.",
        "Maracanãzinho ao lado recebe jogo de vôlei e show.",
        "1950 deixou trauma de final perdida pro Uruguai.",
        "Gramado natural exige manutenção cara todo mês.",
        "Entorno vive dia de jogo com barbeiro e ambulante.",
        "Fla-Flu é derby que nasceu neste endereço.",
        "Cristo Redentor aparece ao fundo em foto aérea do entorno.",
        "Quem entra no túnel de vestiário sente cheiro de grama e suor.",
    ],
    "COPACABANA": [
        "Calçada de ondas em preto e branco marca minha orla.",
        "Bairro carioca famoso entre Atlântico e morro.",
        "Hotel Copacabana Palace abriga turista de luxo na avenida.",
        "Fort de Copacabana vende pão de queijo com vista pro mar.",
        "Réveillon estica faixa de areia com palco e fogos.",
        "Posto dois e posto seis viraram ponto de encontro.",
        "Garota de Ipanema morava perto, mas minha praia é vizinha.",
        "Bicicleta alugada percorre ciclovia até Ipanema.",
        "Morro do Cantagalo divide limite com Ipanema.",
        "Domingo tem futebol de areia e vôlei na beira da água.",
        "Avenida Atlântica tem seis faixas e trânsito pesado.",
        "Idoso caminha de manhã com roupa de ginástica colorida.",
        "Barraca de quiosque serve água de coco gelada.",
        "Crime de celular assusta turista distraído na calçada.",
        "Concerto de Rod Stewart e Rolling Stones já usou minha areia.",
        "Nome veio de santo padroeiro de uma vila antiga.",
        "Quem senta no muro da praia vê o sol cair atrás do morro.",
    ],
    "CHAPADA DIAMANTINA": [
        "Parque nacional protege cânion e cachoeira na Bahia.",
        "Lençóis é cidade base pra trilha e pousada.",
        "Poço Azul e Poço Encantado brilham com luz filtrada.",
        "Cachoeira da Fumaça cai de mais de trezentos metros.",
        "Morrão e Paty são vilas dentro do roteiro de trekking.",
        "Diamante de garimpo deu fama à região no século XIX.",
        "Gruta da Pratinha pede capacete e água gelada.",
        "Trilha exige guia em trecho de mata fechada.",
        "Altitude traz noite fria mesmo no Nordeste.",
        "Vale do Capão concentra comunidade alternativa e restaurante vegano.",
        "Onça e lobo-guará aparecem em avistamento raro.",
        "Ônibus de Salvador leva horas até a portaria do parque.",
        "Pico do Barbado é ponto mais alto da Bahia.",
        "Formação rochosa lembra chapada aberta pro céu.",
        "Turista carrega mochila pesada e botina de trilha.",
        "Cachoeira do Buracão exige nado curto em fenda estreita.",
        "Quem mergulha no Poço Azul vê rocha azulada debaixo d'água.",
    ],
}
