# Part 4 of 4 — LUGAR clues (answers 55–70)
CLUES_PART4 = {
    "ATLÂNTIDA": [
        "Civilização lendária afundou no oceano segundo Platão.",
        "Ilha rica desapareceu em um dia e uma noite, diz o mito.",
        "Localização real nunca foi provada por arqueologia.",
        "Documentário especulativo adora mapa sonar do Atlântico.",
        "Nome virou sinônimo de paraíso perdido submerso.",
        "Filme e série usam tecnologia avançada como enredo.",
        "Santorini e Creta aparecem como candidata na teoria.",
        "Pseudociência vende curso sobre continente esquecido.",
        "Platão descreveu em diálogo Timaeus e Critias.",
        "Piloto de avião não acha ruína circular confirmada.",
        "Aquaman e DC Comics ressuscitaram reino submarino fictício.",
        "Bermudas às vezes entram na mesma conversa conspiratória.",
        "Filósofo grego situou além das Colunas de Hércules.",
        "Nenhum povo moderno fala idioma atlante comprovado.",
        "Expedição submarina acha rocha vulcânica, não palácio.",
        "Lenda alimenta romance de aventura desde século XIX.",
        "Quem busca mapa antigo sonha achar portal debaixo d'água.",
    ],
    "ASGARD": [
        "Reino dos deuses nórdicos flutua na mitologia germânica.",
        "Thor brande martelo e protege ponte do arco-íris.",
        "Odin governa com corvo e busca sabedoria em sacrifício.",
        "Loki traz caos entre aesir e vanir.",
        "Marvel transformou cidade dourada em disco voador no cinema.",
        "Valquíria leva guerreiro morto ao salão de banquete.",
        "Yggdrasil conecta nove reinos na cosmologia viking.",
        "Ragnarok profetiza fim do mundo em batalha final.",
        "Bifrost liga mundo humano Midgard ao palácio divino.",
        "Edda poética e prosa narram genealogia divina.",
        "Elenco de Vingadores popularizou visual sci-fi recente.",
        "Heimdall guarda portal com olho que vê longe.",
        "Mjolnir só levanta quem é digno, diz a regra.",
        "Viking real cremava herói em barco, não achava palácio no céu.",
        "Jogo God of War visitou versão nórdica do reino.",
        "Serpente Jörmungandr circunda mundo na profecia.",
        "Quem assiste filme vê arco-íris servir de estrada no céu.",
    ],
    "VENEZA": [
        "Cidade italiana construída sobre ilhas no Adriático.",
        "Gôndola desliza em canal estreito entre palazzo antigo.",
        "Praça San Marco concentra pomba, café caro e basílica.",
        "Carnaval de máscara vende traje elaborado na loja.",
        "Acqua alta alaga calçada quando maré sobe no outono.",
        "Ponte dos Suspiros liga prisão ao palácio ducal.",
        "Vaporetto funciona como ônibus aquático de linha.",
        "Murano exporta vidro soprado colorido.",
        "Labirinto de beco perde turista sem GPS.",
        "Carnevale atrai turista antes da Quaresma.",
        "Arquitetura bizantina brilha em mosaico dourado.",
        "População local diminuiu com aluguel caro e turismo massivo.",
        "Barco taxi substitui carro; não existe rua para trânsito comum.",
        "Biennale de arte ocupa pavilhão a cada dois anos.",
        "Ponte Rialto cruza Grand Canal com loja de joia.",
        "História marítima ligou comércio oriental à Europa.",
        "Quem paga gôndola ouve canto opcional enquanto remo inclina.",
    ],
    "DUBAI": [
        "Cidade dos Emirados Árabes ergueu arranha-céu no deserto.",
        "Burj Khalifa detém título de prédio mais alto do mundo.",
        "Shopping com pista de ski indoor quebra calor de quarenta graus.",
        "Palmeira artificial estende bairro residencial no mar.",
        "Ouro vende-se em vitrine do souk tradicional.",
        "Migrante trabalha construção e hotel em escala enorme.",
        "Metrô automatizado corre acima do viaduto.",
        "Jumeirah Beach recebe turista europeu no inverno.",
        "Petróleo financiou boom antes do turismo e do financeiro.",
        "Fountain show dança água sincronizada à música.",
        "Código de vestimenta pede modéstia em certa área pública.",
        "Iate e carro de luxo estacionam na avenida.",
        "Desert safari vende duna, camel ride e jantar árabe.",
        "Expo 2020 deixou legado de pavilhão futurista.",
        "Ar condicionado gelado contrasta calor seco lá fora.",
        "Voo conecta hub da Emirates a continente inteiro.",
        "Quem sobe no observatório do Burj vê deserto e mar num só olhar.",
    ],
    "LAS VEGAS": [
        "Cidade no deserto de Nevada vende cassino e show.",
        "Strip concentra hotel temático com réplica de monumento.",
        "Neon pisca o tempo todo; sol forte domina o dia.",
        "Casino não tem relógio na parede de propósito.",
        "Casamento rápido com Elvis impersonator é clichê turístico.",
        "Fountain do Bellagio sincroniza água com música clássica.",
        "Desert Inn e outros deram lugar a resort gigante.",
        "Jogo legal atrai adulto; criança fica no arcade.",
        "Convenção corporativa lota hotel midweek.",
        "Helicóptero noturno sobrevoa luz até o horizonte.",
        "Grand Canyon fica a algumas horas de carro ou avião.",
        "Buffet all you can eat alimenta turista 24 horas.",
        "Cirque du Soleil instalou residência permanente aqui.",
        "Calor seco de julho passa de quarenta graus na calçada.",
        "What happens here slogan virou meme global.",
        "Caça-níquel faz barulho de moeda mesmo em era digital.",
        "Quem entra no cassino pela primeira vez perde noção de hora.",
    ],
    "HOLLYWOOD": [
        "Bairro de Los Angeles virou metônimo de cinema americano.",
        "Letreiro branco no morro marca entrada simbólica.",
        "Walk of Fame embute estrela com nome de artista no chão.",
        "Estúdio Paramount e Warner ficam nos arredores.",
        "Oscar entrega estatueta dourada todo fevereiro.",
        "Turista busca autógrafo em frente a cinema TCL Chinese.",
        "Produtor e agente almoçam em restaurante de Sunset Boulevard.",
        "Paparazzi persegue celebridade em convertible.",
        "Filme blockbuster estreia com premiere e tapete vermelho.",
        "Dream factory descreve fábrica de fantasia do século XX.",
        "Crise de streaming mudou bilheteria de sala.",
        "Dublê queima pneu na perseguição filmada em rua.",
        "Calçada da fama inclui cantor, diretor e personagem animado.",
        "Letreiro no morro originalmente anunciava loteamento imobiliário.",
        "Beverly Hills fica perto, mas é bairro apartado.",
        "Imigrante europeu fundou estúdio que virou império.",
        "Quem sobe trilha perto do letreiro leva garrafa d'água e protetor.",
    ],
    "VATICANO": [
        "Menor estado soberano do mundo dentro de Roma.",
        "Papa católico governa como chefe espiritual global.",
        "Basílica de São Pedro domina praça com obelisco central.",
        "Capela Sistina guarda teto pintado por Michelangelo.",
        "Guarda Suíça veste uniforme listrado na entrada.",
        "Museus aqui exibem coleção acumulada por séculos.",
        "Fumaça branca ou preta anuncia conclave na chaminé.",
        "Latim ainda aparece em documento oficial.",
        "Trato de Laterano me tornou cidade independente em 1929.",
        "Papa aparece no balcão para Urbi et Orbi.",
        "Jardins fechados abrigam rádio e heliporto papal.",
        "Turista fila horas para ver Pietà de Michelangelo.",
        "Biblioteca guarda manuscrito medieval raro.",
        "Euro circula como moeda apesar do tamanho minúsculo.",
        "Coluna da praça foi trazida do Egito antigo.",
        "Audiência semanal reúne peregrino de país distante.",
        "Quem entra na fila da basílica veste ombro coberto por respeito.",
    ],
    "ILHA DE PÁSCOA": [
        "Rapa Nui fica isolada no Pacífico sul, perto do Chile.",
        "Moai de pedra olha para interior da ilha em fila.",
        "Voo longo parte de Santiago ou Tahiti com escala.",
        "Polinésio habitou antes da chegada europeia.",
        "Mistério de transporte das estátuas gera teoria de tronco.",
        "Vulcão Rano Raraku era pedreira dos monumentos.",
        "Linguagem rapanui ainda sobrevive entre morador.",
        "Turismo controlado protege patrimônio frágil.",
        "Gado e cavalo pasta entre moai caído.",
        "Festival Tapati celebra cultura local no verão.",
        "Deforestação antiga associada ao colapso social.",
        "Oceano aberto rodeia; continente mais próximo fica longe.",
        "UNESCO listou patrimônio cultural da humanidade.",
        "Pedra compactada pesa tonelada na estátua completa.",
        "Sunrise em Ahu Tongariki vira foto clássica.",
        "Internet lenta chegou tarde comparada ao continente.",
        "Quem caminha entre moai sente vento salgado e silêncio estranho.",
    ],
    "ILHAS GALÁPAGOS": [
        "Arquipélago equatorial pertence ao Equador sul-americano.",
        "Darwin observou tentilhão e desenvolveu ideia evolutiva.",
        "Tartaruga gigante vive século e pesa centenas de quilos.",
        "Iguana marinha mergulha e come alga nas rochas.",
        "Turista paga taxa de entrada e guia obrigatório.",
        "Vulcão ativo moldou paisagem de lava preta.",
        "Fauna não tem medo humano por isolamento longo.",
        "Voo de Quito ou Guayaquil pousa em pista pequena.",
        "Biodiversidade única motivou parque nacional.",
        "Barco cruzeiro faz roteiro ilha a ilha.",
        "Pesca ilegal e espécie invasora ameaçam equilíbrio.",
        "Equador continental fica a cerca de mil quilômetros oeste.",
        "Leão marinho brinca perto de snorkel na baía.",
        "Centro Charles Darwin pesquisa conservação local.",
        "Nome veio de cavalos domésticos que baleeiros soltaram.",
        "Sol na linha do equador queima pele mesmo com vento.",
        "Quem nada com pinguim Galápagos lembra que está no hemisfério sul.",
    ],
    "MONTE KILIMANJARO": [
        "Montanha mais alta da África fica na Tanzânia.",
        "Três cones vulcânicos formam silhueta solitária na savana.",
        "Neve no cume contrasta calor na base equatorial.",
        "Trilha Marangu ou Machame leva dias até o topo.",
        "Porter carrega mochila e cozinha acampamento.",
        "Altitude causa mal da montanha em subida rápida.",
        "Uhuru Peak marca ponto mais alto para bandeira de foto.",
        "Parque nacional protege floresta montana e fauna.",
        "Elefante e búfalo aparecem na savana ao redor.",
        "Hemingway escreveu conto com neve africana no título.",
        "Glaciar encolhe com aquecimento global documentado.",
        "Guia exige taxa e registro antes da caminhada.",
        "Cafeicultor planta na encosta inferior fértil.",
        "Céu estrelado no acampamento compensa frio noturno.",
        "Volcão dorme, mas geologia ainda marca origem.",
        "Summit night start exige headlamp e casaco grosso.",
        "Quem chega ao amanhecer no topo vê nuvem abaixo dos pés.",
    ],
    "ALPES": [
        "Cordilheira europeia corta França, Suíça, Itália e Áustria.",
        "Mont Blanc é pico famoso na fronteira franco-italiana.",
        "Estação de ski vende forfait no inverno europeu.",
        "Chocolate suíço e queijo fondue alimentam turista.",
        "Túnel ferroviário longo atravessa rocha sob montanha.",
        "Vacas com sino pastam prado verde no verão.",
        "Teleférico sobe até mirante com neve o ano todo em parte.",
        "Tour de France pedala subida íngreme todo julho.",
        "Avalanche e neve controlada exigem patrulha.",
        "Chalet de madeira abriga hóspede após dia de pista.",
        "Rio Rin e Po nascem em geleira alpina.",
        "Yodel e corno alpino soam em festival folclórico.",
        "Fronteira nacional cruza crista sem controle em trilha.",
        "Glaciar encolhe; poste marca onde gelo existia décadas atrás.",
        "Montanha Matterhorn aparece em logo de chocolate.",
        "Verão traz trilha de hiking e paragliding.",
        "Quem desce esquiando sente sol forte mesmo com luva gelada.",
    ],
    "CARIBE": [
        "Mar tropical banha arco de ilha do Golfo ao Atlântico.",
        "Areia branca e água turquesa vendem resort all inclusive.",
        "Cruzeiro desembarca turista por dia em porto.",
        "Reggae e calypso saem de alto-falante na praia.",
        "Furacão ameaça temporada de junho a novembro.",
        "Cuba, Jamaica e Barbados são nomes na playlist de férias.",
        "Rum, coco e peixe frito compõem cardápio de bar.",
        "Snorkel mostra coral e peixe colorido raso.",
        "Pirata do século XVII assombrou rota comercial.",
        "Dólar americano ou euro circula em ilha turística.",
        "Cruise ship ancorado parece prédio flutuante.",
        "Merengue e salsa animam noite de hotel.",
        "Barco a vela liga ilha pequena a grande.",
        "Sol queima pele clara que esqueceu filtro.",
        "História de colonização europeia e escravidão marca cultura.",
        "Turista brasileiro compara preço com Nordeste às vezes.",
        "Quem deita na rede ouve vento leve e mar batendo devagar.",
    ],
    "PETRA": [
        "Cidade nabateia esculpida em rocha rosada na Jordânia.",
        "Fachada do Tesouro aparece ao fim do desfiladeiro estreito.",
        "Siq é gorge alto que estreita antes da revelação.",
        "Indiana Jones buscou Santo Graal em cena filmada aqui.",
        "Camelo e burro oferecem ride até o mosteiro no alto.",
        "Civilização controlou rota de incenso e especiaria.",
        "Túmulo e teatro romano ficam espalhados no vale.",
        "UNESCO listou patrimônio antes da fama hollywoodiana.",
        "Cor rosa vem de mineral na arenito ao entardecer.",
        "Beduino local guia trilha e vende lenço.",
        "Entrada cara inclui dia inteiro de caminhada.",
        "Wadi Rum fica perto com deserto vermelho de filme.",
        "Água canalizada antiga sustentou população no deserto.",
        "Turista bebe chá de hortelã na tenda de descanso.",
        "Escadaria sub centenas de degraus até Ed-Deir.",
        "Anfiteatro pequeno recebia assembleia na rocha.",
        "Quem passa pelo Siq ouve eco antes de ver fachada inteira.",
    ],
    "MURO DAS LAMENTAÇÕES": [
        "Resto de templo judaico antigo em Jerusalém oriental.",
        "Pedra grande empilhada sem argamassa visível moderna.",
        "Peregrino encosta testa e deixa bilhete na fresta.",
        "Sábado traz reza intensa antes do pôr do sol.",
        "Muçulmano reza do outro lado no complexo da Mesquita Al-Aqsa.",
        "História de destruição por império romano no ano 70.",
        "Soldado israelense vigia acesso com checkpoint.",
        "Menorá simbólica lembra candelabro do templo perdido.",
        "Bar mitzvah comemora com torah perto das pedras.",
        "Turista cobre ombro e perna por respeito no local.",
        "Escavação arqueológica continua no túnel ao lado.",
        "Conflito político envolve soberania da cidade sagrada.",
        "Pedra ocidental é nome técnico além do apelido em português.",
        "Festa judaica concentra multidão apertada na praça.",
        "Noite ilumina pedra enquanto família reza baixo.",
        "Cidade velha de Jerusalém circunda o complexo.",
        "Quem toca a pedra fria sente camada de ora acumulada em séculos.",
    ],
    "HAVAÍ": [
        "Arquipélago vulcânico no Pacífico norte, estado americano.",
        "Surf nasceu em onda longa de Waikiki e North Shore.",
        "Camisa hawaiana colorida e lei de flores recebem visitante.",
        "Kilauea já derramou lava visível em parque nacional.",
        "Hula dança conta mito com movimento de mão.",
        "Fuso horário fica horas atrás da costa continental dos EUA.",
        "Poke bowl de atum cru vende-se no mercado.",
        "Batalha naval de Pearl Harbor marcou entrada dos EUA na Segunda Guerra.",
        "Vulcão Mauna Kea abriga observatório no topo.",
        "Brisa alísio traz chuva num lado da ilha e sol no outro.",
        "Turista japonês e continental americano divide resort.",
        "Placa tectônica move ilha lentamente sobre hotspot.",
        "Ukulele e slack-key guitar animam luau de hotel.",
        "Custo de vida alto importa comida do continente.",
        "Honolulu concentra aeroporto e arranha-céu na ilha Oahu.",
        "Baleia jubarte aparece em passeio de barco no inverno.",
        "Quem aprende a cumprimentar ouve aloha como olá e adeus.",
    ],
    "SYDNEY": [
        "Opera House com telhado branco em forma de vela domina baía.",
        "Harbour Bridge permite climb com arnese até o arco.",
        "Bondi Beach recebe surfista e bronzeado no leste.",
        "Capital de New South Wales, não capital federal australiana.",
        "Canberra fica inland; eu fico na costa sudeste.",
        "Fogo de artifício de Ano Novo estoura sobre a baía primeiro.",
        "Tram e ferry cruzam porto azul com skyline.",
        "Koala aparece em zoológico taronga com vista pro centro.",
        "Inverno australiano é junho a agosto, sol ainda aparece.",
        "Multiculturalismo traz comida vietnamita e libanesa em suburb.",
        "Cricket preenche estádio oval no verão esportivo.",
        "Queen Victoria Building vende moda em prédio histórico.",
        "Blue Mountains fica a day trip de carro ou trem.",
        "Torre giratória serve jantar com vista no centro comercial.",
        "Immigration histórica passou pelo cais como entrada.",
        "Real australiano paga café flat white caro.",
        "Quem sobe no ferry olha opera e ponte numa curva só.",
    ],
}
