# Part 2 of 4 — LUGAR clues (answers 19–36)
CLUES_PART2 = {
    "JALAPÃO": [
        "Fico no Tocantins, longe da costa brasileira.",
        "Dunas douradas e fervedouro viraram roteiro de ecoturismo.",
        "Formação rochosa dos Morros Vermelhos parece Marte terrestre.",
        "Cachoeira da Formiga tem poço convidativo no meio do cerrado.",
        "Serras Gerais abrigam nascente de rio importante.",
        "Trilha de 4x4 conecta vilas pequenas sem asfalto.",
        "Buriti e cerrado queimam fácil na seca do verão.",
        "Mateiros e São Félix servem de base pra visitante.",
        "Região ganhou fama depois de novela e documentário.",
        "Meu Poço Azul compete com lagoa clara do Nordeste em foto.",
        "Guia local é quase obrigatório nas trilhas longas.",
        "Peixe assado e mandioca alimentam mesa de fazenda.",
        "Noite estrelada compensa falta de sinal de celular.",
        "Parque estadual local protege parte do meu território.",
        "Turista combina roteiro com Palmas, capital do estado.",
        "Areia fina sobe bota em dia seco sem chuva.",
        "Quem flutua no fervedouro sente água empurrando o corpo pra cima.",
    ],
    "BONITO": [
        "Mato Grosso do Sul me vende como capital do ecoturismo.",
        "Rio da Prata deixa snorkel ver peixe como aquário natural.",
        "Gruta do Lago Azul brilha com luz azul profunda.",
        "Flutuação em rio de água cristalina exige colete e botina.",
        "Abismo Anhumas desce rapel antes do mergulho escuro.",
        "Balneário municipal controla número de visitantes por dia.",
        "Peixe piraputanga e dourado aparecem na água transparente.",
        "Cachoeira do Mimoso e Boca da Onça vendem day use caro.",
        "Calcário da região filtra água e deixa rio limpo.",
        "Passeio de balão ao amanhecer virou foto de Instagram.",
        "Campo Grande fica a algumas horas de carro da cidade.",
        "Restaurante local serve pacu assado e sobremesa de doce de leite.",
        "Chuva fora de época pode cancelar flutuação por segurança.",
        "Agência exige reserva com semanas de antecedência no verão.",
        "Buraco das Araras concentra arara-vermelha no penhasco.",
        "Nome da cidade promete beleza, e turista cobra isso.",
        "Quem desce a escada da gruta azul sente umidade gelada na pele.",
    ],
    "RIO AMAZONAS": [
        "Sou o maior rio em volume de água do planeta.",
        "Nasço nos Andes peruanos e deságua no Atlântico.",
        "Manaus recebe encontro das águas com afluente escuro.",
        "Barco de carga e passageiro sobem meus afluentes por semanas.",
        "Bacia amazônica abriga floresta tropical gigante.",
        "Pirarucu e tucunaré vivem nas águas quentes.",
        "Cheia sobe até árvore e muda mapa das comunidades.",
        "Fronteira entre Brasil, Peru e Colômbia cruza meu leito.",
        "Navigation por GPS ainda erra canal na época de vazante.",
        "Rio Negro entra pelo lado brasileiro com cor escura.",
        "Exportação de grão desce por hidrovia até porto.",
        "Indígena e ribeirinho pescam tambaqui na margem.",
        "Loreto e Belém são cidades grandes na minha margem.",
        "Boto cor-de-rosa aparece em passeio turístico em Manaus.",
        "Seca expõe praia de areia no meio do leito largo.",
        "Nome vem de língua indígena ligada a tribo feminina guerreira.",
        "Quem cruza de barco pequeno sente correnteza puxando pro oceano.",
    ],
    "SERRA DA CAPIVARA": [
        "Parque nacional no Piauí guarda pintura rupestre antiga.",
        "Sítio arqueológico prova gente na América antes do consenso antigo.",
        "Pedra com desenho de animal e humano cobre abrigo rochoso.",
        "Caatinga seca rodeia cânion de arenito vermelho.",
        "Boqueirão da Pedra Furada é trilha clássica com guia.",
        "UNESCO listou meu conjunto como Patrimônio Cultural.",
        "Niéde Guidon liderou escavação que mudou debate acadêmico.",
        "São Raimundo Nonato é porta de entrada pra visitante.",
        "Sol forte exige chapéu e garrafa d'água o dia todo.",
        "Fóssil e arte rupestre aparecem no mesmo roteiro museológico.",
        "Vegetação rala esconde lobo-guará e preá.",
        "Acesso de estrada de terra ainda assusta carro baixo.",
        "Idade das pinturas passa de dez mil anos em estudo.",
        "Turista dorme em pousada simples na cidade vizinha.",
        "Documentário já mostrou arqueólogo limpando camada fina de areia.",
        "Nome Capivara veio de fauna local, não do roedor gigante só.",
        "Quem entra no abrigo da Toca do Boqueirão vê cervo pintado na parede.",
    ],
    "BELO HORIZONTE": [
        "Capital mineira, apelidada carinhosamente de BH.",
        "Praça da Liberdade concentra museu e café ao ar livre.",
        "Mineirão recebeu jogo de Copa e show de grande porte.",
        "Pão de queijo e tutu de feijão saem de padaria o tempo todo.",
        "Conspiracy e Savassi movem bar e balada de fim de semana.",
        "Oscar Niemeyer desenhou conjunto na Pampulha com igreja curva.",
        "Serra do Curral aparece ao fundo em foto da cidade.",
        "Trânsito engarrafou depois que carro virou regra.",
        "Mercado Central vende cachaça artesanal e doce de leite.",
        "Clima seco de inverno resseca nariz de quem vem do litoral.",
        "Metrô ainda é curto, ônibus carrega a maior parte da cidade.",
        "Autódromo de rua já recebeu Fórmula 1 nos anos 70.",
        "Feira de artesanato no domingo enche parque municipal.",
        "Mineiro fala devagar e chama estranho de uai no meio da frase.",
        "Região metropolitana inclui Contagem e Betim industrial.",
        "Inhotim fica a uma hora de carro e puxa turista de arte.",
        "Quem pede mesa no boteco pede long neck gelada e torresmo.",
    ],
    "CHAPADA DOS VEADEIROS": [
        "Parque nacional em Goiás protege cerrado e cachoeira.",
        "Alto Paraíso de Goiás é base pra trilha e pousada.",
        "Cachoeira Santa Bárbara tem poço verde famoso em foto.",
        "Formação de quartzito brilha sob sol de meio-dia.",
        "Trilha do Vale da Lua parece pedra lunar à beira de rio.",
        "Altitude perto de mil e quinhentos metros traz noite fria.",
        "Lobo-guará e lêmure-do-cerrado aparecem em avistamento raro.",
        "Entrada exige guia credenciado em trechos protegidos.",
        "Cerrado queima em seca e renasce verde na chuva.",
        "Brasília fica a poucas horas de carro pro sul.",
        "Poço do Diabo e Janela são quedas no roteiro clássico.",
        "Comunidade de São Jorge concentra restaurante e hostel.",
        "Estrela cadente brilha forte longe da luz da capital.",
        "UNESCO reconheceu cerrado como hotspot de biodiversidade.",
        "Turista leva repelente contra mosquito de trilha.",
        "Pedra esculpida pelo vento forma piscina natural em sequência.",
        "Quem caminha até Santa Bárbara molha pé na água morna do poço.",
    ],
    "TORRE EIFFEL": [
        "Estrutura de ferro treliçado domina skyline parisiense.",
        "Gustave Eiffel assinou engenharia da minha montagem em 1889.",
        "Exposição Universal de Paris me lançou como cartão postal.",
        "Três andares recebem restaurante, museu e vista.",
        "Luz dourada à noite pisca a cada hora cheia.",
        "Fila de turista contorna minha base mesmo na chuva.",
        "Elevador inclinado sobe até o segundo pavimento.",
        "Original era temporária; a cidade decidiu me manter.",
        "Altura passa de trezentos metros com antena no topo.",
        "Champ de Mars é o gramado onde criança corre em volta.",
        "Casal pede beijo no mirante com cidade lá embaixo.",
        "Pintura marrom clara exige manutenção constante contra ferrugem.",
        "Nome do engenheiro virou sinônimo de torre metálica.",
        "Réveillon parisiense explode fogos bem ao meu lado.",
        "Vendedor ambulante vende miniatura de chaveiro o dia todo.",
        "Trem de metrô passa embaixo pela estação Bir-Hakeim.",
        "Quem sobe de escada conta degraus até cansar a panturrilha.",
    ],
    "ESTÁTUA DA LIBERDADE": [
        "Fico na entrada do porto de Nova York.",
        "Ilha pequena recebe balsa cheia de turista todo dia.",
        "Tocha erguida simboliza acolhida a imigrante.",
        "Presente da França aos Estados Unidos no século XIX.",
        "Frederic Auguste Bartholdi esculpiu meu rosto de cobre.",
        "Pedestal de pedra foi financiado com doação popular.",
        "Coroa com sete pontas representa continente na iconografia.",
        "Estrutura interna usou engenharia de Gustave Eiffel.",
        "Inauguração em 1886 coincidiu com centenário americano.",
        "Museu dentro da base explica imigração e construção.",
        "Helicóptero turístico rodeia minha silhueta verde.",
        "Tablet na mão traz data de independência em algarismo romano.",
        "Ellis Island ficava perto, processando quem desembarcava.",
        "Restauração trocou armadura interna no fim do século XX.",
        "Neblina do porto às vezes esconde minha silhueta da foto.",
        "Filme e novela americana me usam como plano de abertura.",
        "Quem lê o poema na base lembra exilados chegando de barco.",
    ],
    "GRANDE MURALHA DA CHINA": [
        "Fortificação de pedra e tijolo serpenteia montanha asiática.",
        "Construída ao longo de séculos para conter invasão do norte.",
        "Trecho perto de Pequim recebe turista com teleférico.",
        "Mutianyu e Badaling são nomes de acesso famosos.",
        "Largura permite soldado marchar ou cavalo passar em trecho.",
        "Visível do espaço é mito, mas comprimento impressiona mapa.",
        "Dinastia Ming reforçou muitos quilômetros que restam hoje.",
        "Degrau íngreme exige tênis e garrafa d'água.",
        "Neblina de inverno esconde torre de vigia na crista.",
        "Patrimônio Mundial da UNESCO lista meu conjunto.",
        "Vendedor ambulante vende cachecol e água no meio da subida.",
        "Nome em mandarim fala em barreira longa, não muro único.",
        "Restauração moderna reconstruiu pedra em trecho turístico.",
        "Soldado de terracota no museu lembra mesmo império antigo.",
        "Outono pinta folha vermelha nos arredores do norte.",
        "Guia conta história de sinal de fumaça entre torres.",
        "Quem caminha horas na crista vê vale dos dois lados da pedra.",
    ],
    "COLISEU": [
        "Anfiteatro oval de Roma ainda recebe fila de turista.",
        "Gladiador e animal lutaram aqui no Império Romano.",
        "Arco de travertino sobreviveu a terremoto e saque de pedra.",
        "Capacidade antiga passava de cinquenta mil espectadores.",
        "Hypogeum subterrâneo escondia elevador de palco.",
        "Patrimônio da UNESCO e símbolo da Itália.",
        "Nome popular veio de colossal, não de coluna.",
        "Restauração recente limpou fachada de poluição urbana.",
        "Metro linha B para na estação com meu nome.",
        "Noite iluminada vira cartão postal ao lado do Fórum.",
        "Tour noturno desce ao subsolo com guia de fone.",
        "Imperador Vespasiano iniciou obra; Tito inaugurou.",
        "Cristão associou local a martírio, embora debate continue.",
        "Pedra reaproveitada construiu palácio renascentista na cidade.",
        "Verão traz sol forte e chapéu obrigatório na fila.",
        "Arena central era madeira coberta de areia sobre hipogeum.",
        "Quem entra pelo corredor escuro ouve eco de multidão antiga.",
    ],
    "PIRÂMIDES DE GIZÉ": [
        "Três monumentos de pedra erguem-se no deserto egípcio.",
        "Quéops é a maior e mais antiga das três clássicas.",
        "Esfinx com corpo de leão guarda o complexo ao lado.",
        "Túmulo de faraó do Antigo Império, não de faraó medieval.",
        "Bloco de calcário pesado foi empilhado sem motor moderno.",
        "Cairo moderno aparece no horizonte poluído atrás.",
        "Camelo e vendedor ambulante cercam turista na chegada.",
        "Interior estreito leva corredor até câmara do sarcófago.",
        "Patrimônio listado pela UNESCO como conjunto.",
        "Alinhamento astronômico gerou teoria de observatório estelar.",
        "Granito de Aswan entrou em revestimento interno.",
        "Turista sobe degrau íngreme até entrada estreita.",
        "Areia e vento corroem base há milênios.",
        "Luz e som à noite projetam história na fachada.",
        "Engenheiro ainda debate rampa externa ou interna.",
        "Giza fica a poucos quilômetros do centro urbano atual.",
        "Quem encosta a mão na pedra sente calor seco do deserto.",
    ],
    "TAJ MAHAL": [
        "Mármore branco brilha às margens do rio Yamuna.",
        "Mausoléu mogol foi pedido por imperador por amor à esposa.",
        "Agra, na Índia, recebe visitante de todo o subcontinente.",
        "Cúpula central e minaretes simétricos formam meu perfil.",
        "Jardim charbagh divide quatro caminhos em cruz.",
        "Inscrição caligráfica corânica cobre portal.",
        "Mármore muda tom com luz do amanhecer e entardecer.",
        "Construção levou mais de vinte anos no século XVII.",
        "Patrimônio Mundial da UNESCO desde 1983.",
        "Pé descalço ou sapatenha cobre entrada sagrada.",
        "Poluição urbana exigiu limpeza química na fachada.",
        "Interior abriga túmulo falso visível e câmara real abaixo.",
        "Filme bollywood e documentário usam minha silhueta.",
        "Lua cheia abre visita noturna limitada em temporada.",
        "Artesão persa e indiano combinaram técnicas na decoração.",
        "Nome da esposa Mumtaz Mahal entrou no título do monumento.",
        "Quem reflete no espelho d'água tira foto simétrica clássica.",
    ],
    "MACHU PICCHU": [
        "Cidadela inca fica no alto dos Andes peruanos.",
        "Terrace de pedra sustentava plantação em encosta íngreme.",
        "Huayna Picchu é o pico que aparece atrás nas fotos.",
        "Descoberta ampla para o mundo veio com Hiram Bingham em 1911.",
        "Trem de Cusco sobe até Aguas Calientes na base.",
        "Nevoeiro de manhã esconde e revela muro de pedra.",
        "Patrimônio Mundial e uma das sete maravilhas modernas.",
        "Intihuatana é pedra ritual no centro arqueológico.",
        "Sem rodovia direta; trilha Inca exige reserva e guia.",
        "Llama pasta gramado e posa para selfie de turista.",
        "Altitude perto de dois mil e quatrocentos metros cansou pulmão.",
        "Império Inca abandonou antes da chegada espanhola plena.",
        "Portão do Sol marca entrada tradicional da trilha.",
        "Uruguay e Brasil ficam longe; vizinho é Bolívia e Colômbia.",
        "Aguas termais na vila aliviam perna após subida.",
        "Pedra encaixada sem argamassa aguenta terremoto andino.",
        "Quem espera nascer do sol no mirador congela antes de fotografar.",
    ],
    "BIG BEN": [
        "Torre do relógio fica no Palácio de Westminster em Londres.",
        "Sino de treze toneladas dá nome popular ao conjunto.",
        "Elizabeth Tower é o nome oficial da torre desde 2012.",
        "Mostrador azul e dourado marca hora pro Parlamento.",
        "Badalada do sino pesado ecoa a cada quarto de hora na cidade.",
        "Restauração longa cobriu torre com andaime recentemente.",
        "Thames corre perto; Westminster Bridge leva turista.",
        "Gótico victoriano define fachada de pedra escura.",
        "Filme britânico usa minha silhueta como plano de Londres.",
        "Visitante estrangeiro confunde nome do sino com o da torre.",
        "Mecanismo de 1859 ainda precisa de winding manual histórico.",
        "Noite iluminada reflete no rio com Houses of Parliament.",
        "Bandeira Union Jack sobe quando Parlamento está em sessão.",
        "Metrô para em Westminster a poucos passos.",
        "Nome homenageia Sir Benjamin Hall, comissário de obras.",
        "Explosão da Segunda Guerra danificou sala do relógio.",
        "Quem ouve badalada ao meio-dia conta doze toques no ar frio.",
    ],
    "TORRE DE PISA": [
        "Campanário de mármore inclina na Toscana italiana.",
        "Pisa fica na região onde nasceu Galileu.",
        "Inclinação veio de fundação mole em solo arenoso.",
        "Construção começou no século XII e demorou séculos.",
        "Oito andares de arcos românicos circundam o eixo.",
        "Engenheiro moderno estabilizou inclinação sem endireitar total.",
        "Turista imita foto empurrando torre com a mão.",
        "Piazza dei Miracoli reúne catedral e batistério ao lado.",
        "Sino no topo ainda marca hora pra cidade.",
        "Patrimônio da UNESCO lista praça inteira.",
        "Estudante estrangeiro enche universidade local.",
        "Leaning Tower é apelido em inglês que colou no mundo.",
        "Degrau interno sobe em espiral até mirante inclinado.",
        "Restauração removeu terra de um lado para frear queda.",
        "Trem regional liga Florença em menos de uma hora.",
        "Galileu teria soltado pesos do topo, conta a lenda.",
        "Quem sobe sente chão inclinado e vista torta da cidade.",
    ],
    "PARTENON": [
        "Templo de mármore coroa a Acrópole de Atenas.",
        "Dedicado a Atena, deusa patrona da cidade grega.",
        "Colunas dóricas formam fileira dupla na fachada.",
        "Pericles mandou reconstruir após invasão persa.",
        "Frieze e metope contavam mito e batalha na pedra.",
        "Explosão de pólvora otomana danificou estrutura no século XVII.",
        "Elgin marbles no British Museum geram disputa diplomática.",
        "Restauração atual usa mármore novo claro ao lado do antigo.",
        "Patrimônio da UNESCO protege a Acrópole inteira.",
        "Turista sobe ladeira calçada sob sol forte do verão.",
        "Propylaea é portal monumental na entrada da colina.",
        "Erechtheion com cariátides fica perto no mesmo complexo.",
        "Democracia ateniense floresceu quando eu era templo vivo.",
        "Noite iluminada mostra coluna contra céu escuro.",
        "Filme e documentário usam minha fileira como símbolo de Grécia.",
        "Interior abrigou estátua de ouro e marfim de Fídias.",
        "Quem caminha entre as colunas ouve guia contar mito de Poseidon.",
    ],
    "STONEHENGE": [
        "Círculo de pedra ergue-se no campo inglês de Wiltshire.",
        "Bloco de sarsen pesa tonelada e veio de longe.",
        "Alinhamento com solstício de verão atrai druida moderno.",
        "Idade estimada passa de quatro mil anos antes de Cristo.",
        "Patrimônio Mundial da UNESCO lista meu conjunto.",
        "Teoria vai de templo astronômico a cemitério tribal.",
        "Cerca paga controla acesso; visita guiada explica camada.",
        "Neolítico britânico ergueu antes de pirâmide egípcia.",
        "Trilithon forma portal de duas verticais e lintel.",
        "Avebury fica perto com círculo de pedra maior e menos famoso.",
        "Neblina matinal esconde silhueta em foto misteriosa.",
        "Escavação recente achou osso humano no entorno.",
        "Solstício de junho lota estacionamento antes do amanhecer.",
        "Nome em inglês fala pedra suspensa, não rocha cortada.",
        "Somerset e Glastonbury ficam na região turística.",
        "Réplica decorativa aparece em jardim de curioso pelo mundo.",
        "Quem assiste sol nascer atrás do lintel sente vento frio no rosto.",
    ],
    "CATARATAS DO NIÁGARA": [
        "Quedas gigantes separam lago Erie e Ontario.",
        "Fronteira entre Canadá e Estados Unidos corta o rio.",
        "Barco Maid of the Mist veste capa e encosta na névoa.",
        "Três quedas principais: Ferradura, Americanas e Bridal Veil.",
        "Gerador hidrelétrico aproveita volume enorme de água.",
        "Casino e torre de observação recebem turista o ano todo.",
        "Inverno congela borda e forma cascata de gelo parcial.",
        "Lua de mel americana listou meu nome por décadas.",
        "Arco-íris aparece no vapor quando sol bate reto.",
        "Toronto fica a poucas horas de carro da margem canadense.",
        "Helicóptero sobrevoa barulho ensurdecedor da queda.",
        "Ponte arco-íris liga cidades dos dois países.",
        "Barco de borracha subiu trilho antes do passeio moderno.",
        "Indígena Haudenosaunee habitou região antes da colonização.",
        "Filme e série usam queda como cenário de ação.",
        "Volume de água cai a cada segundo em tonelada incontável.",
        "Quem entra no barco molhado guarda capa azul de lembrança.",
    ],
}
