# Cards 1-24 for raw-pessoa.json rewrite
PART1 = [
    {
        "answer": "AYRTON SENNA",
        "clues": [
            "No automobilismo, ainda sou nome que todo mundo cita.",
            "Nasci em São Paulo, capital, em março de 1960.",
            "Ganhei a vida pilotando monoposto na Fórmula 1.",
            "Levei três títulos mundiais consecutivos pra casa.",
            "Alain Prost foi meu rival mais marcante nos anos 80.",
            "Morri no GP de San Marino, em maio de 1994.",
            "Em Donington Park, 93, venci numa chuva histórica.",
            "Meu capacete trazia faixas nas cores da bandeira brasileira.",
            "Defendi a McLaren quando brilhei mais forte.",
            "Antes disso, passei pela Lotus e pela Toleman.",
            "Meu irmão Leonardo também chegou a correr na categoria.",
            "Tem instituto com meu nome ligado a criança e educação.",
            "Uma curva de Interlagos leva meu sobrenome.",
            "Em Mônaco, minha pole de 88 virou lenda.",
            "Quando morri, o país parou na frente da televisão.",
            "Sou ídolo máximo do kart e da F1 no Brasil.",
            "Meu primeiro nome tem seis letras e começa com A.",
        ],
    },
    {
        "answer": "PELÉ",
        "clues": [
            "No futebol, me apelidam de Rei.",
            "Nasci em Três Corações, Minas Gerais.",
            "Cresci jogando na Vila Belmiro, em Santos.",
            "Marquei mais de mil gols oficiais na carreira.",
            "Ganhei três Copas do Mundo vestindo amarelinha.",
            "Meu nome de registro é Edson Arantes do Nascimento.",
            "Quase toda vida profissional foi no Peixe.",
            "Fui jogar nos EUA, no New York Cosmos.",
            "Meu apelido veio de brincadeira com um goleiro Bil.",
            "Sou o único tricampeão mundial como jogador de campo.",
            "O gol mil saiu de pênalti no Maracanã, em 1969.",
            "A camisa dez da seleção ficou famosa comigo.",
            "Recebi prêmio de Atleta do Século em votação grande.",
            "Meu pai, Dondinho, também foi atacante.",
            "Tem museu sobre mim no litoral paulista.",
            "Muita gente me chama só de O Rei.",
            "Meu apelido tem quatro letras e acento no E.",
        ],
    },
    {
        "answer": "ANITTA",
        "clues": [
            "Sou cantora e empresária do Rio.",
            "Comecei postando vídeo e dançando funk.",
            "Hoje misturo pop, funk e colaboração internacional.",
            "Já fui jurada em programa de talentos na TV aberta.",
            "Meu nome artístico parece diminutivo carinhoso.",
            "Gravo em português, espanhol e inglês.",
            "Subi palco de festival grande fora do Brasil.",
            "Tenho documentário sobre minha trajetória na Netflix.",
            "Meus clipes costumam viralizar com coreografia.",
            "Envolver explodiu no TikTok em 2022.",
            "Já lancei disco com artistas gringos de peso.",
            "Administro marca e negócios além do palco.",
            "Mudei cabelo e estética várias vezes na carreira.",
            "Nasci no Honório Gurgel, zona norte carioca.",
            "Meu nome civil é Larissa de Macedo Machado.",
            "Sou uma das brasileiras que mais chartou lá fora.",
            "Meu nome artístico repete a letra T duas vezes seguidas.",
        ],
    },
    {
        "answer": "CHAVES",
        "clues": [
            "Sou menino pobre de uma vila mexicana na TV.",
            "Durmo num barril na entrada do pátio.",
            "Roberto Gómez Bolaños me criou nos anos 70.",
            "Fico falando foi sem querer querendo o tempo todo.",
            "Seu Madruga é meu amigo adulto preferido.",
            "Quico é o vizinho rico que me irrita.",
            "Professora Girafales dá aula na escolinha da vila.",
            "Há décadas entro na TV brasileira de tarde.",
            "Uso chapéu marrom que virou ícone.",
            "Quem me interpreta na vida real é adulto baixinho.",
            "Tenho versão desenho animado com minha turma.",
            "No pátio tem poço onde a gente brinca.",
            "Adoro sanduíche de presunto e refrigerante.",
            "Em espanhol me chamam El Chavo del Ocho.",
            "A Dona Clotilde, bruxa do 71, mora perto.",
            "Na ficção, nunca completo aniversário de adulto.",
            "Meu nome em português soa igual a um verbo no presente.",
        ],
    },
    {
        "answer": "CLEÓPATRA",
        "clues": [
            "Fui rainha do Egito no fim da era helenística.",
            "Sou lembrada por aliança com Roma.",
            "Tive relação política e afetiva com Júlio César.",
            "Depois vivi romance e guerra com Marco Antônio.",
            "Minha corte ficava em Alexandria, no delta do Nilo.",
            "Pintaram meus olhos com kohl, diz a tradição.",
            "Lendas falam da minha eloquência em várias línguas.",
            "Na história, preferi morte a humilhação romana.",
            "Contam que uma serpente entrou na história do meu fim.",
            "Pertencia à dinastia dos Ptolomeus.",
            "Elizabeth Taylor me interpretou no cinema clássico.",
            "Shakespeare escreveu peça com meu nome no título.",
            "Meu nome virou sinônimo de rainha sedutora.",
            "O Nilo alimentava o império que eu governava.",
            "Fui a última faraó de linhagem ptolomaica.",
            "Apareço em série, filme e documentário sem parar.",
            "Meu nome termina em A e tem acento no O.",
        ],
    },
    {
        "answer": "SHERLOCK HOLMES",
        "clues": [
            "Sou detetive de ficção criado por Doyle.",
            "Moro em Londres, na famosa rua Baker.",
            "Meu endereço mais citado é o 221B.",
            "Dr. Watson narra quase todas as minhas histórias.",
            "Resolvo caso olhando detalhe que ninguém viu.",
            "Uso lupa e raciocínio deductivo como marca.",
            "Toco violino quando a cabeça precisa de silêncio.",
            "Professor Moriarty aparece como meu inimigo intelectual.",
            "Senhora Hudson cuida do fogão e do aluguel.",
            "Digo que é elementar, meu caro Watson.",
            "Nas adaptações, apareço com chapéu deer-stalker.",
            "Meu irmão Mycroft é ainda mais preguiçoso que eu.",
            "Fumo cachimbo nas ilustrações antigas.",
            "Vivi casos como o cão das Baskerville.",
            "Basil Rathbone e Benedict Cumberbatch já me interpretaram.",
            "Muita gente me aponta como maior detetive literário.",
            "Meu sobrenome rima com homes em inglês americano.",
        ],
    },
    {
        "answer": "NEYMAR",
        "clues": [
            "Sou atacante brasileiro de drible e criação.",
            "Nasci em Mogi das Cruzes, Grande São Paulo.",
            "Estourei no Santos antes de ir pra Europa.",
            "Formei trio ofensivo histórico no Barcelona.",
            "Depois joguei anos no Paris Saint-Germain.",
            "Transferência minha pro PSG quebrou recorde de valor.",
            "Visto a dez da seleção em Copas e eliminatórias.",
            "Em 2014, fratura nas costas me tirou da semifinal em casa.",
            "Comemoro gol com dancinha que vira meme.",
            "Meu pai tem o mesmo primeiro nome que eu.",
            "Morei temporada na Arábia, no Al-Hilal.",
            "Tenho milhões de seguidores no Instagram.",
            "Na infância me chamavam Juninho ou Ney.",
            "Brilhei ao lado de Messi e Suárez no Barça.",
            "Já disputei duas finais de Champions.",
            "Me apontam como herdeiro da era Ronaldo e Ronaldinho.",
            "Meu sobrenome tem cinco letras e acento no I.",
        ],
    },
    {
        "answer": "XUXA",
        "clues": [
            "Sou apresentadora que marcou infância nos anos 80 e 90.",
            "Comecei como modelo e rainha de baile.",
            "Apresentei programa infantil diário na Globo.",
            "Meu parque de diversões virou marca nacional.",
            "Cantei Paquito, Ilariê e Lua de Cristal.",
            "Tive relacionamento famoso com jogador da seleção.",
            "Lancei produtos de beleza e linha infantil.",
            "Meu apelido veio de brincadeira de infância.",
            "Maria da Graça Meneghel é meu nome completo.",
            "Gravei disco que vendeu milhões de cópias.",
            "Também atuei em cinema e novela.",
            "Fui jurada e mentora em reality musical.",
            "Meu time de Paquitas dançava ao meu lado.",
            "Nasci em Santa Rosa, no Rio Grande do Sul.",
            "Hoje também produzo conteúdo digital.",
            "Muita gente cresceu acordando com meu programa.",
            "Meu apelido tem quatro letras e repete a mesma vogal.",
        ],
    },
    {
        "answer": "LULA",
        "clues": [
            "Sou metalúrgico que virou presidente do Brasil.",
            "Nasci em Caetés, interior de Pernambuco.",
            "Cresci pobre e perdi dedo num acidente de fábrica.",
            "Fundei sindicato e parti dos trabalhadores.",
            "Fui presidente por dois mandatos seguidos, 2003 a 2010.",
            "Programas sociais como Bolsa Família marcaram meu governo.",
            "Voltei à presidência em 2023 depois de anos difíceis.",
            "Meu nome completo é Luiz Inácio Lula da Silva.",
            "Casei com Janja na vida recente.",
            "Já fui preso e depois absolvido em processos da lava jato.",
            "Uso gravata vermelha e sorriso largo em palanque.",
            "Disputei eleição apertada contra Bolsonaro em 2022.",
            "Meu apelido de três letras virou marca política.",
            "Fui criticado e idolatrado em proporções iguais.",
            "Represento esquerda brasileira mais votada da história.",
            "Falo com sotaque nordestino marcante.",
            "Meu apelido é diminutivo do meu segundo nome.",
        ],
    },
    {
        "answer": "GISELE BÜNDCHEN",
        "clues": [
            "Sou modelo brasileira que dominou passarela mundial.",
            "Nasci em Horizontina, no Rio Grande do Sul.",
            "Comecei nova na indústria da moda nos anos 90.",
            "Fui angel da Victoria's Secret por longa temporada.",
            "Casei com quarterback americano Tom Brady.",
            "Tenho irmã gêmea chamada Patricia.",
            "Defendo meio ambiente e alimentação consciente.",
            "Meu sobrenome alemão tem trema no U.",
            "Apareci na capa de revistas de moda do planeta.",
            "Fui uma das modelos mais bem pagas do mundo.",
            "Moro parte do tempo nos EUA e no Brasil.",
            "Já desfilei para grifes como Chanel e Versace.",
            "Retirei e voltei à passarela algumas vezes.",
            "Tenho filhos com o ex-marido americano.",
            "Meu cabelo loiro virou referência de beauty.",
            "Falo sobre saúde mental e rotina de mãe.",
            "Meu primeiro nome tem seis letras e termina em E.",
        ],
    },
    {
        "answer": "SILVIO SANTOS",
        "clues": [
            "Sou dono de emissora e apresentador de domingo.",
            "Nasci Senor Abravanel, filho de imigrantes.",
            "Criei o SBT e programas de auditório.",
            "Distribuo dinheiro ao vivo com envelope e pergunta.",
            "Tenho bordão tipo ma oee e risada própria.",
            "Casamento com Íris e filhas aparecem na mídia.",
            "Comecei vendendo caneta e produto de porta em porta.",
            "Meu programa de domingo dura a tarde inteira.",
            "Já concorri a prefeito de São Paulo.",
            "Tenho parque temático e marca de produtos.",
            "Apresento Tele Sena e sorteios nacionais.",
            "Meu sobrenome artístico veio de apelido de rádio.",
            "Sou um dos maiores comunicadores da TV brasileira.",
            "Faço pegadinha, dança e entrevista no mesmo dia.",
            "Cabelo branco e terno claro viraram meu visual.",
            "Muita família brasileira liga a TV quando eu entro.",
            "Meu nome artístico tem cinco letras e dois S.",
        ],
    },
    {
        "answer": "MICHAEL JACKSON",
        "clues": [
            "Sou cantor americano apelidado de Rei do Pop.",
            "Comecei criança nos Jackson 5.",
            "Lancei Thriller, disco mais vendido da história.",
            "Inventei moonwalk que todo mundo imita.",
            "Luva branca e jaqueta militar viraram meu uniforme.",
            "Moro em Neverland, fazenda com parque.",
            "Meu visual mudou muito ao longo das décadas.",
            "Cantei Billie Jean, Beat It e Smooth Criminal.",
            "Irmãos Janet e Jermaine também são famosos.",
            "Gravei clipe longo de zumbi que assustou geração.",
            "Fui acusado e absolvido em casos que dividiram opinião.",
            "Morri em 2009, aos 50 anos, em Los Angeles.",
            "Influenciei pop, dança e videoclipes modernos.",
            "Usava luvas brancas brilhantes em palco.",
            "Meu filho mais conhecido se apelida Blanket.",
            "Homenagens postumas continuam no mundo inteiro.",
            "Meu primeiro nome tem sete letras e começa com M.",
        ],
    },
    {
        "answer": "ALBERT EINSTEIN",
        "clues": [
            "Sou físico alemão naturalizado americano.",
            "Formulei a relatividade que mudou a física.",
            "A equação E igual mc ao quadrado leva minha assinatura.",
            "Ganhei Nobel de Física por efeito fotoelétrico.",
            "Meu cabelo branco em foto virou cartaz de gênio.",
            "Trabalhei no patent office antes da fama.",
            "Fugi da Alemanha nazista e fui pros EUA.",
            "Assinei carta alertando sobre bomba atômica.",
            "Toco violino nas horas vagas, dizem os relatos.",
            "Língua de Einstein virou nome de síndrome rara.",
            "Nasci em Ulm, na Alemanha, em 1879.",
            "Professor em Princeton marcou meus últimos anos.",
            "Frases minhas sobre imaginação circulam em pôster.",
            "Relatividade geral explicou desvio de luz no eclipse.",
            "Meu sobrenome virou sinônimo de inteligência.",
            "Morri em 1955, deixando legado científico enorme.",
            "Meu sobrenome tem oito letras e começa com E.",
        ],
    },
    {
        "answer": "HARRY POTTER",
        "clues": [
            "Sou menino bruxo de óculos redondos.",
            "J.K. Rowling me criou nos livros dos anos 90.",
            "Cresci em armário sob escada dos tios.",
            "Entrei na escola de magia Hogwarts.",
            "Minha cicatriz em forma de raio no rosto me marca.",
            "Ron e Hermione são meus melhores amigos.",
            "Luto contra Lord Voldemort, o sem nariz.",
            "Sou da casa Grifinória no chapéu seletor.",
            "Jogo quadribol como apanhador.",
            "Coruja branca me traz carta de admissão.",
            "Professores como Dumbledore e Snape moldam minha vida.",
            "Filmes me interpretaram com Daniel Radcliffe.",
            "Meu patrono é um cervo, igual ao do meu pai.",
            "Derroto o vilão finalmente na batalha de Hogwarts.",
            "Tenho saga de sete livros traduzida pro mundo.",
            "Meu nome de batismo é Harry, sem segundo sobrenome mágico.",
            "Meu sobrenome também é nome de utensílio de cozinha.",
        ],
    },
    {
        "answer": "CRISTIANO RONALDO",
        "clues": [
            "Sou português, atacante e ídolo global.",
            "Nasci na ilha da Madeira, em Funchal.",
            "Comecei no Sporting antes de ir pro Manchester United.",
            "Usei a sete no Real Madrid por muitos anos.",
            "Ganhei várias Bolas de Ouro na carreira.",
            "Sou artilheiro histórico de Champions League.",
            "Já joguei na Juventus e voltei ao United.",
            "Hoje atuo na Arábia, no Al-Nassr.",
            "Comemoro gol pulando e gritando Siuuu.",
            "Tenho filhos e vida pública bem exposta.",
            "Corpo definido virou marca de fitness.",
            "Disputei rivalidade épica com argentino do Barça.",
            "Capitão da seleção portuguesa por longa data.",
            "Free kick e cabeceio são meus cartões visita.",
            "Número sete me acompanha na maioria dos clubes.",
            "Redes sociais me colocam entre atletas mais seguidos.",
            "Meu primeiro nome tem nove letras e acento no A.",
        ],
    },
    {
        "answer": "LIONEL MESSI",
        "clues": [
            "Sou argentino, camisa dez por excelência.",
            "Nasci em Rosário, em 1987.",
            "Passei infância tratando déficit de hormônio do crescimento.",
            "Barcelona me acolheu e formou por quase duas décadas.",
            "Ganhei sete Bolas de Ouro vestindo azulgrana.",
            "Levantei a Copa do Mundo de 2022 pela Argentina.",
            "Formei MSN com Neymar e Suárez.",
            "Drible curto e canhota são minha assinatura.",
            "Hoje jogo nos EUA, no Inter Miami.",
            "Barba e tatuagem no braço marcam meu visual adulto.",
            "Sou artilheiro histórico do Barcelona.",
            "Choro ao ganhar título que faltava na seleção.",
            "Antonela é minha esposa de longa data.",
            "Apelido La Pulga me segue desde criança.",
            "Levantei Champions várias vezes no Camp Nou.",
            "Muitos me colocam como maior da história do futebol.",
            "Meu apelido de três letras termina com I.",
        ],
    },
    {
        "answer": "STEVE JOBS",
        "clues": [
            "Sou cofundador da Apple no garagem.",
            "Nasci em San Francisco e fui adotado.",
            "Lancei Macintosh, iPod, iPhone e iPad.",
            "Apresentava produto de jeans e tênis preto.",
            "Saí e voltei à Apple nos anos 90.",
            "Pixar também faz parte da minha história.",
            "Frase stay hungry stay foolish me acompanha.",
            "Exigi design simples e controle total do ecossistema.",
            "Morri em 2011 de câncer de pâncreas.",
            "Wozniak era o parceiro técnico nos primórdios.",
            "Campanha Think Different usou meu rosto indireto.",
            "Keynote virou show de palco no setor tech.",
            "Revolucionei música com loja digital no iPod.",
            "Celular sem teclado físico foi aposta minha.",
            "Biografia oficial saiu com autor Walter Isaacson.",
            "Silicon Valley me trata como ícone de inovação.",
            "Meu sobrenome de quatro letras rima com lobs em inglês.",
        ],
    },
    {
        "answer": "MARILYN MONROE",
        "clues": [
            "Sou atriz americana símbolo dos anos 50.",
            "Meu nome artístico esconde Norma Jeane Baker.",
            "Cabelo loiro platinado e vestido branco viraram ícone.",
            "Cantei happy birthday para presidente Kennedy.",
            "Estrelou comédias como Some Like It Hot.",
            "Fotos de calendário me tornaram sex symbol.",
            "Casamentos com Joe DiMaggio e Arthur Miller deram manchete.",
            "Morri jovem em Los Angeles, em 1962.",
            "Misterios sobre minha morte alimentam teorias.",
            "Andy Warhol repetiu meu rosto em serigrafia.",
            "Falava com voz doce e andar balançado.",
            "Hollywood me explorou e me consagrou ao mesmo tempo.",
            "Pintura vermelha nos lábios era marca registrada.",
            "Frase sobre Chanel número cinco me acompanha.",
            "Nasci em Los Angeles, filha de mãe instável.",
            "Hoje sou pôster clássico de cinema e pop.",
            "Meu nome artístico tem duas palavras, ambas com M.",
        ],
    },
    {
        "answer": "FRIDA KAHLO",
        "clues": [
            "Sou pintora mexicana de autorretrato intenso.",
            "Sobrevivi a acidente de ônibus na juventude.",
            "Sobrancelha junta e flores no cabelo me identificam.",
            "Casei duas vezes com muralista Diego Rivera.",
            "Minha casa azul virou museu na Cidade do México.",
            "Dor crônica e política entraram nas minhas telas.",
            "Vestido tehuana aparece em muitos quadros meus.",
            "Macacos, cervos e colar de espinhos são motivos meus.",
            "Exposição de roupas minhas lotou museu recentemente.",
            "Sou ícone feminista e latina no mundo.",
            "Nasci em Coyoacán, em 1907 ou 1910, debatem.",
            "Relacionamento tumultuado com Diego virou lenda.",
            "Pintei deitada no leito quando não podia levantar.",
            "Unibrow virou símbolo de autenticidade.",
            "Hollywood já fez filme sobre minha vida.",
            "Meu primeiro nome tem cinco letras e acento no I.",
            "Meu sobrenome tem cinco letras e rima com solo.",
        ],
    },
    {
        "answer": "LEONARDO DA VINCI",
        "clues": [
            "Sou artista e inventor do Renascimento italiano.",
            "Pintei Mona Lisa, retrato enigmático no Louvre.",
            "Desenhei homem vitruviano dentro do círculo.",
            "Estudei anatomia dissecando cadáveres.",
            "Projeto de helicóptero e paraquedas saiu do meu caderno.",
            "Last Supper decora convento em Milão.",
            "Nasci em Vinci, na Toscana, por volta de 1452.",
            "Trabalhei para Ludovico Sforza e outros patronos.",
            "Escrevi anotações em espelho, da direita pra esquerda.",
            "Sou exemplo de homem renascentista completo.",
            "Código Da Vinci, livro bestseller, usa meu nome.",
            "Engenharia e arte misturavam na minha mesa.",
            "Nunca terminei tudo que comecei, dizem.",
            "Obra Adoração dos Magi ficou inacabada.",
            "Morto em Amboise, na França, sob proteção real.",
            "Meu primeiro nome remete a uma tartaruga ninja.",
            "Meu sobrenome é nome de cidade pequena na Itália.",
        ],
    },
    {
        "answer": "NAPOLEÃO BONAPARTE",
        "clues": [
            "Fui imperador dos franceses no início do século 19.",
            "Nasci em Corsica, ilha mediterrânea.",
            "Subi de oficial a general na Revolução Francesa.",
            "Coronado em Notre-Dame com coroa na mão.",
            "Conquistei boa parte da Europa antes de cair.",
            "Campanha na Rússia foi meu grande desastre.",
            "Exilado em Elba, voltei nos Cem Dias.",
            "Waterloo encerrou meu retorno definitivo.",
            "Terminei dias em Santa Helena, ilha remota.",
            "Código civil francês leva influência minha.",
            "Sou baixo na estatura só na piada, não na história.",
            "Chapéu bicorne aparece em todo retrato meu.",
            "Joséphine foi esposa famosa nos primeiros anos.",
            "Retratos me mostram mão dentro do casaco.",
            "Legião de Honra foi instituição minha.",
            "Estrategista de batalha ainda estudado em academias.",
            "Meu nome virou tamanho de chapéu na gíria.",
        ],
    },
    {
        "answer": "DARTH VADER",
        "clues": [
            "Sou vilão de capa negra da saga espacial.",
            "Respirar alto com máscara assusta criança.",
            "Antes fui Jedi chamado Anakin Skywalker.",
            "Obi-Wan foi meu mestre na juventude.",
            "Luke descobre ser meu filho no clímax.",
            "Palpatine me seduziu pro lado sombrio.",
            "Empunho sabre de luz vermelho.",
            "Capacete preto esconde rosto queimado.",
            "Comando Estrela da Morte sob minhas ordens.",
            "Falei famosa frase sobre ser pai.",
            "George Lucas me criou nos anos 70.",
            "James Earl Jones emprestou voz grave.",
            "Duelo com Luke perdeu mão na Cloud City.",
            "Redenção final ao salvar filho do imperador.",
            "Sou action figure mais vendido de ficção.",
            "Imperial March toca quando entro em cena.",
            "Meu título de cavaleiro começa com D e termina com R.",
        ],
    },
    {
        "answer": "HOMER SIMPSON",
        "clues": [
            "Sou pai de família amarela de Springfield.",
            "Trabalho na usina nuclear como inspetor de segurança.",
            "Esposa Marge tem cabelo azul em torre.",
            "Filho Bart faz pegadinha e leva detenção.",
            "Filha Lisa toca saxofone e tira dez.",
            "Bebê Maggie chupa chupeta o tempo todo.",
            "Adoro donut rosa e cerveja Duff.",
            "Grito Doh quando algo dá errado.",
            "Matt Groening me desenhou nos anos 80.",
            "Série animada entra no ar há décadas.",
            "Chefe Carl Carlson e Lenny são colegas de plantão.",
            "Bar do Moe é meu point de fim de tarde.",
            "Já tive centenas de empregos temporários no episódio.",
            "Couch gag abre quase todo capítulo.",
            "Sou gordo, careca e de coração mole.",
            "Frase eu não fiz nada vira meme eterno.",
            "Meu nome lembra poeta grego da Ilíada.",
        ],
    },
    {
        "answer": "BEYONCÉ",
        "clues": [
            "Sou cantora americana apelidada Queen Bey.",
            "Comecei no grupo Destiny's Child.",
            "Casada com rapper Jay-Z, somos power couple.",
            "Lancei álbum visual Lemonade cheio de política.",
            "Show no Super Bowl dividiu e empolgou metade do país.",
            "Single Formation virou hino em protestos.",
            "Blue Ivy é minha filha mais famosa.",
            "Coreografia e figurino são parte do meu show.",
            "Cantei Halo, Crazy in Love e Single Ladies.",
            "Atuei em Dreamgirls no cinema.",
            "Nasci em Houston, Texas, em 1981.",
            "Coachella me chamou de HBCU quando subi palco.",
            "Controlo gravação, dança e imagem com mão firme.",
            "Grammy acumulado me coloca entre artistas mais premiadas.",
            "Roupa dourada e corpo escultural viraram marca.",
            "Fãs formam Beyhive nas redes.",
            "Meu nome artístico tem acento agudo no último E.",
        ],
    },
]
