# Cards 49-70 for raw-pessoa.json rewrite
PART3 = [
    {
        "answer": "SUPER-HOMEM",
        "clues": [
            "Sou herói de capa vermelha dos quadrinhos.",
            "Vim de planeta Krypton bebê em foguete.",
            "Criei-me em Kansas com nome Clark Kent.",
            "Jornal Daily Planet é meu emprego de dia.",
            "Lois Lane é repórter que me paquera.",
            "Voo, visão de calor e superforça me definem.",
            "Kryptonita verde me derruba.",
            "Lex Luthor é inimigo bilionário calvo.",
            "Símbolo S no peito virou ícone global.",
            "Jerry Siegel e Joe Shuster me criaram nos 30.",
            "Filme com Christopher Reeve marcou geração.",
            "Justice League reúne amigos heróis comigo.",
            "Traje azul colado e botas vermelhas.",
            "Identidade secreta protege família adotiva.",
            "Sou chamado Man of Steel em inglês.",
            "Salvo Metropolis de desastre toda semana.",
            "Meu nome traduzido começa com Super e termina com homem.",
        ],
    },
    {
        "answer": "BATMAN",
        "clues": [
            "Sou vigilante noturno de Gotham City.",
            "Orfão bilionário, herdei Wayne Enterprises.",
            "Moro na mansão com mordomo Alfred.",
            "Capa e máscara de morcego assustam bandido.",
            "Robin já foi meu parceiro sidekick.",
            "Cinto com gadget substitui superpoder.",
            "Joker é inimigo psicopata recorrente.",
            "Batmovel é carro que garagem esconde.",
            "Pais morreram em beco após opera.",
            "Treinei corpo e mente pelo mundo.",
            "Sinal de morcego no céu me chama.",
            "Filme Nolan me escureceu pro cinema adulto.",
            "Nunca uso arma de fogo, regra minha.",
            "Catwoman vive entre aliada e romance.",
            "Bob Kane e Bill Finger me desenharam.",
            "Sou membro fundador da Liga da Justiça.",
            "Meu símbolo animal voa de cabeça pra baixo.",
        ],
    },
    {
        "answer": "MICKEY MOUSE",
        "clues": [
            "Sou rato de luva branca da Disney.",
            "Walt Disney e Ub Iwerks me desenharam.",
            "Steamboat Willie foi meu estreia sonora.",
            "Minnie é minha namorada de laço.",
            "Donald e Pateta são amigos de aventura.",
            "Orelhas redondas viraram logo da empresa.",
            "Falo com voz aguda em desenho clássico.",
            "Parque temático usa minha silhueta na entrada.",
            "Shorts vermelhos e sapato amarelo grande.",
            "Apareço em caneta, camiseta e relógio infantil.",
            "Sorriso aberto esconde dente separado.",
            "Filme Fantasia me colocou como mago aprendiz.",
            "Sou mascote mais famoso do cinema animado.",
            "Língua portuguesa me chama Mickey igual.",
            "Copyright da Disney protege meu desenho.",
            "Cachorro Pluto é meu pet, não fala.",
            "Meu nome rima com tricky em inglês americano.",
        ],
    },
    {
        "answer": "ELSA",
        "clues": [
            "Sou princesa de Arendelle com poder de gelo.",
            "Frozen, filme da Disney, contou minha história.",
            "Let It Go virou hino de criança em todo lugar.",
            "Irmã Anna é morena e otimista ao meu lado.",
            "Isolada no castelo por medo de machucar.",
            "Vestido azul cristal brilha na transformação.",
            "Olaf, boneco de neve, é amigo cômico.",
            "Cabelo loiro platinado em trança depois solto.",
            "Beijo verdadeiro não me salva; amor de irmã sim.",
            "Idina Menzel emprestou voz na versão americana.",
            "Sequel Frozen 2 me mandou pro bosque encantado.",
            "Criança canta minha música no karaokê.",
            "Coroa de gelo aparece quando perco controle.",
            "Príncipe Hans me traiu no primeiro filme.",
            "Sou rainha, não princesa, no fim da trama.",
            "Brinquedo e fantasia de Halloween me imitam.",
            "Meu nome tem quatro letras e acento no E.",
        ],
    },
    {
        "answer": "GANDHI",
        "clues": [
            "Liderei independência da Índia sem violência.",
            "Nasci em Porbandar, em 1869.",
            "Estudei direito na Inglaterra jovem.",
            "Satyagraha, resistência não violenta, era meu método.",
            "Caminhada do sal desafiou imposto britânico.",
            "Vivia simples, com tecido de fiar.",
            "Jejum político usei para acalmar conflito.",
            "Assassinado em 1948 por extremista.",
            "Apelido Mahatma significa grande alma.",
            "Óculos redondos e bengala aparecem em foto.",
            "Influenciei Mandela e King nos movimentos civis.",
            "Defendi castas e hinduísmo de formas criticadas hoje.",
            "Filme de 1982 me deu Oscar de melhor filme.",
            "Figura em cédula indiana atual.",
            "Protesto pacífico virou modelo mundial.",
            "Sou símbolo de liberdade colonial.",
            "Meu sobrenome tem seis letras e acento no I.",
        ],
    },
    {
        "answer": "NELSON MANDELA",
        "clues": [
            "Fui presidente sul-africano pós-apartheid.",
            "Passei 27 anos preso na Robben Island.",
            "Lutei contra segregação racial legal.",
            "Libertado em 1990, virei ícone global.",
            "Nobel da Paz dividi com De Klerk.",
            "Apelido Madiba me conhece na África.",
            "Camisa com número 46664 lembra prisão.",
            "Rugby World Cup 95 unifiquei país simbolicamente.",
            "Casamento com Graça Machel marcou últimos anos.",
            "Morri em 2013, velório mundial.",
            "Partido ANC foi minha casa política.",
            "Autobiografia Long Walk to Freedom vendeu milhões.",
            "Rosto aparece em mural e moeda.",
            "Perdoei algoz sem esquecer injustiça.",
            "Estatua em Pretoria me mostra punho fechado.",
            "Sou referência máxima de reconciliação.",
            "Meu primeiro nome tem seis letras e acento no O.",
        ],
    },
    {
        "answer": "CHE GUEVARA",
        "clues": [
            "Sou revolucionário argentino de barba e boina.",
            "Nasci Ernesto Guevara em Rosário.",
            "Médico de formação, virei guerrilheiro.",
            "Revolução Cubana me colocou ao lado de Fidel.",
            "Foto de Korda virou pôster de dormitório.",
            "Diário de moto narrou juventude na América.",
            "Tentei exportar revolta pra Bolívia.",
            "Capturado e executado em 1967.",
            "Restos mortais geraram mistério por décadas.",
            "Símbolo de esquerda e de merchandising ao mesmo tempo.",
            "Beret preta com estrela vermelha me identifica.",
            "Críticos me veem autoritário; admiradores, herói.",
            "Letras de música e camiseta carregam meu rosto.",
            "Bolívia guarda memorial onde caí.",
            "Frase até a vitória sempre circula.",
            "Nome Che veio de interjeição argentina.",
            "Meu apelido de três letras termina com E.",
        ],
    },
    {
        "answer": "MARIE CURIE",
        "clues": [
            "Sou cientista polonesa naturalizada francesa.",
            "Descobri polônio e rádio com Pierre.",
            "Primeira mulher a ganhar Nobel.",
            "Única pessoa com Nobel em duas ciências diferentes.",
            "Pesquisa em radioatividade abriu campo novo.",
            "Morri de anemia por exposição a radiação.",
            "Filha Irène também ganhou Nobel depois.",
            "Guerra: levei raio X pra frente de batalha.",
            "Nasci Maria Skłodowska em Varsóvia, 1867.",
            "Laboratório simples virou museu em Paris.",
            "Homens da academia resistiram à minha entrada.",
            "Nome Curie entrou na tabela periódica indireto.",
            "Biografia recente destacou luta como mulher.",
            "Frase sobre entender menos teme menos me cita.",
            "Coffin de chumbo protegeu corpo radioativo.",
            "Sou ícone STEM para meninas no mundo.",
            "Meu nome Marie é versão francesa de Maria.",
        ],
    },
    {
        "answer": "WILLIAM SHAKESPEARE",
        "clues": [
            "Sou dramaturgo inglês do século 16 e 17.",
            "Nasci em Stratford-upon-Avon.",
            "Romeu e Julieta escrevi sobre amor proibido.",
            "Hamlet questiona ser ou não ser.",
            "Globe Theatre encenou minhas peças em Londres.",
            "Macbeth traz bruxa e ambição assassina.",
            "Soneto 18 compara amada ao verão.",
            "Criou milhares de palavras usadas até hoje.",
            "Retiro em Stratford marcou meus últimos anos.",
            "Identidade real às vezes gera teoria conspiratória.",
            "Rei Lear e Otelo são tragédias centrais.",
            "Comédia como Sonho de Verão encanta palco.",
            "Templo Poets' Corner guarda busto meu.",
            "Escola obriga leitura minha no ensino médio.",
            "Adaptação cinema e musical não para.",
            "Sou autor mais citado em língua inglesa.",
            "Meu sobrenome tem onze letras e termina com E.",
        ],
    },
    {
        "answer": "MOZART",
        "clues": [
            "Sou compositor austríaco prodígio clássico.",
            "Nasci em Salzburgo em 1756.",
            "Pai Leopold me levou turnê europeia criança.",
            "Requiem inacabado envolveu mistério póstumo.",
            "Opera O Barbeiro de Sevilha não é minha; Magic Flute sim.",
            "Sinfonia dos Jupiter e Eine kleine Nachtmusik são hits.",
            "Rivalidade com Salieri virou filme exagerado.",
            "Morri pobre em Viena aos 35.",
            "Escrevi mais de seiscentas obras em vida curta.",
            "Concerto para piano e quarteto de cordas abundam.",
            "Figaro e Don Giovanni são óperas centrais.",
            "Nome completo Wolfgang Amadeus soa pomposo.",
            "Música clássica de elevador muitas vezes sou eu.",
            "Constanze foi esposa e viúva controversa.",
            "Partitura manuscrita gira em leilão caro.",
            "Sou símbolo de gênio precoce universal.",
            "Meu sobrenome tem seis letras e acento no A.",
        ],
    },
    {
        "answer": "SIGMUND FREUD",
        "clues": [
            "Sou psiquiatra vienense pai da psicanálise.",
            "Nasci em Moravia, imperio austro-húngaro.",
            "Divã e associação livre eram meu método.",
            "Inconsciente, id, ego e superego nomeei.",
            "Interpretação dos Sonhos publiquei em 1900.",
            "Edipo e complexo paterno ficaram famosos.",
            "Charuto e barba branca em foto clássica.",
            "Discípulos Jung e Adler romperam comigo.",
            "Exilei-me em Londres fugindo nazismo.",
            "Morri em 1939, mandíbula por câncer.",
            "Sexualidade infantil teoria chocou época.",
            "Freudian slip virou expressão comum.",
            "Consultório reconstruído virou museu.",
            "Crítica moderna questiona base científica.",
            "Influenciei literatura, cinema e terapia.",
            "Cocaína usei em experimento, arrependido depois.",
            "Meu sobrenome de cinco letras rima com mood.",
        ],
    },
    {
        "answer": "BILL GATES",
        "clues": [
            "Sou cofundador da Microsoft no garagem.",
            "Nasci em Seattle em 1955.",
            "Windows colocou PC em mesa do planeta.",
            "Casamento com Melinda virou fundação filantrópica.",
            "Forbes me listou como mais rico por anos.",
            "Depois deixei operação diária da empresa.",
            "Luto contra malária e polio com doação.",
            "Depoimento antitruste nos EUA marcou anos 90.",
            "Paul Allen foi parceiro técnico inicial.",
            "Livro sobre clima saiu na década recente.",
            "Visual óculos e suéter simples na entrevista.",
            "Pandemia me colocou na mira de teoria conspiratória.",
            "Doação bilionária promete doar quase tudo.",
            "Harvard abandonei pra fundar software.",
            "Competição com Steve Jobs virou documentário.",
            "Hoje foco em energia limpa e saúde global.",
            "Meu apelido Bill é diminutivo de William.",
        ],
    },
    {
        "answer": "WALT DISNEY",
        "clues": [
            "Sou animador que criou império do rato.",
            "Nasci em Chicago, cresci no Missouri.",
            "Mickey Mouse saiu da minha mesa de desenho.",
            "Disneyland abriu parque temático na Califórnia.",
            "Snow White foi primeiro longa animado colorido.",
            "Voz minha embaralhada abre some productions.",
            "Ouroscar honorário recebi por contribuição.",
            "Brother Roy cuidou financeiro da empresa.",
            "Morto em 1966, antes de Walt Disney World abrir.",
            "Controvérsias sobre minhas visões políticas persistem.",
            "Steamboat Willie entrou domínio público recentemente.",
            "Frase sonhe grande circula em pôster motivacional.",
            "Estúdio Burbank virou cidade do entretenimento.",
            "Parks espalhados do Orlando a Paris.",
            "Nome virou sinônimo de infância mágica.",
            "Desenho à mão deu lugar ao CGI depois de mim.",
            "Meu sobrenome tem seis letras e acento no E.",
        ],
    },
    {
        "answer": "BRUCE LEE",
        "clues": [
            "Sou lutador e ator de artes marciais.",
            "Nasci em San Francisco, criado em Hong Kong.",
            "Jeet Kune Do foi filosofia que fundei.",
            "Filme Enter the Dragon me levou ao Ocidente.",
            "Corpo seco e grito antes do golpe marcaram.",
            "Nunchaku girava rápido nas cenas.",
            "Morri misteriosamente jovem em 1973.",
            "Filho Brandon também morreu trágico no set.",
            "Influenciei MMA e cinema de ação.",
            "Dragão chinês tatuado virou símbolo meu.",
            "Luta com Chuck Norris ficou clássica em filme.",
            "Quebrei estereótipo de asiático frágil em Hollywood.",
            "Frase ser como água inspira treino.",
            "Demorei a ser reconhecido nos EUA por racismo.",
            "Livros meus sobre arte marcial ainda vendem.",
            "Statue em Hong Kong olha pra baía.",
            "Meu primeiro nome tem cinco letras e acento no U.",
        ],
    },
    {
        "answer": "OPRAH WINFREY",
        "clues": [
            "Sou apresentadora americana de talk show.",
            "Nasci pobre no Mississippi rural.",
            "The Oprah Winfrey Show durou 25 anos.",
            "Book club meu vendia best-seller da noite pro dia.",
            "Entrevista com celebridade virava evento nacional.",
            "Você ganhou um carro virou meme de plateia.",
            "Atriz indicada a Oscar por Cor Púrpura.",
            "Rede OWN carrega meu sobrenome.",
            "Amiga próxima de celebridade e político.",
            "Discurso Golden Globes #MeToo repercutiu.",
            "Filantropia em educação de menina na África.",
            "Magazine O tem capa mensal.",
            "Nome Oprah é misspelling bíblico de Orpah.",
            "Multibilionária autodidata sem diploma tradicional.",
            "Entrevista explosiva com Harry e Meghan recente.",
            "Sou uma das mulheres negras mais influentes do mundo.",
            "Meu sobrenome tem sete letras e acento no E.",
        ],
    },
    {
        "answer": "FREDDIE MERCURY",
        "clues": [
            "Sou vocalista britânico da banda Queen.",
            "Nasci Farrokh Bulsara em Zanzibar.",
            "Bohemian Rhapsody misturou ópera e rock.",
            "Show Live Aid em Wembley entrou pra história.",
            "Bigode e calça justa marcaram palco.",
            "We Will Rock You vira palmas de estádio.",
            "Morri de AIDS em 1991, anunciado antes.",
            "Parceiro Jim Hutton cuidou dos últimos dias.",
            "Range vocal de quatro oitavas falavam.",
            "Piano abria show com intro de Bohemian.",
            "Biopic com Rami Malek ganhou Oscar.",
            "Somebody to Love e Don't Stop Me Now são hits.",
            "Frontman teatral, corpo no centro do spotlight.",
            "Estátua em Montreux olha pro lago.",
            "Fãs colocam flores na casa em Londres.",
            "Sou ícone LGBTQ+ póstumo global.",
            "Meu nome artístico remete a deus romano.",
        ],
    },
    {
        "answer": "LADY GAGA",
        "clues": [
            "Sou cantora americana de pop teatral.",
            "Nasci Stefani Germanotta em Nova York.",
            "Poker Face e Bad Romance dominaram rádio.",
            "Vestido de carne na entrega de prêmio chocou.",
            "Nasceu This Way virou hino de fã Little Monster.",
            "Atuei em Nasce uma Estrela com Bradley Cooper.",
            "Oscar de canção por Shallow marcou cinema.",
            "Super Bowl halftime show trouxe piano e drones.",
            "Voz poderosa vem de treino clássico.",
            "Born This Way Foundation fala de saúde mental.",
            "Visual muda de wig a wig a cada era.",
            "Chromatica e Joanne mostraram fases diferentes.",
            "Parceria com Tony Bennett trouxe jazz.",
            "Fibromialgia e trauma apareceram na vida aberta.",
            "Meu apelido veio de frase da banda Queen.",
            "Turnê Monster Ball lotou arena mundo afora.",
            "Meu nome artístico tem quatro letras no primeiro nome.",
        ],
    },
    {
        "answer": "BOB MARLEY",
        "clues": [
            "Sou cantor jamaicano de reggae.",
            "Nasci em Nine Mile, Jamaica, 1945.",
            "One Love e No Woman No Cry são clássicos.",
            "Rastafari e dreadlock marcaram minha imagem.",
            "The Wailers foi banda que lancei.",
            "Exile on Main St não; Exodus sim, álbum meu.",
            "Tiro no peito quase me matou em 76.",
            "Morri de câncer aos 36, legado gigante.",
            "Filho Ziggy continua música.",
            "Guitarra acústica e groove skank definem som.",
            "Paz e resistência aparecem na letra.",
            "Casa virou museu turístico na Jamaica.",
            "Camiseta com meu rosto vende no mundo.",
            "Redemption Song pede emancipação mental.",
            "Show em Zimbabwe marcou independência africana.",
            "Sou embaixador cultural da Jamaica.",
            "Meu nome Bob é diminutivo de Robert.",
        ],
    },
    {
        "answer": "CHARLIE CHAPLIN",
        "clues": [
            "Sou comediante mudo de bigode e chapéu.",
            "Nasci em Londres, infância pobre.",
            "Personagem Vagabundo virou meu alter ego.",
            "Bengala e passo bambolê marcaram caminhada.",
            "Filme Tempos Modernos criticou fábrica.",
            "City Lights e O Garoto são obras silent.",
            "Falei na tela tarde com ditador satirizado.",
            "Hollywood me expulsou na era McCarthy.",
            "Morri na Suíça, velho e reverenciado.",
            "Compus trilha própria pras comédias.",
            "Mustache pequeno copiado em festa.",
            "Dirigi, produzi e estreei nos filmes.",
            "Influenciei físico comédia até Mr. Bean.",
            "Quatro casamentos deram manchete.",
            "Oscar honorário reconheceu contribuição.",
            "Sou símbolo do cinema mudo clássico.",
            "Meu nome Charlie é apelido de Charles.",
        ],
    },
    {
        "answer": "HOMEM-ARANHA",
        "clues": [
            "Sou herói de Queens com teia e acrobacia.",
            "Picada de aranha radioativa me deu poder.",
            "Tio Ben morreu por culpa minha no começo.",
            "Namorada Mary Jane é ruiva icônica.",
            "Mascote jornal Daily Bugle me difama.",
            "Peter Parker é meu nome de adolescente.",
            "Stan Lee e Steve Ditko me criaram nos 60.",
            "Vilão Duende Verde e Venom me perseguem.",
            "Traje vermelho e azul colado no corpo.",
            "Lanço teia de pulso em prédio.",
            "Sentido aranha apita perigo.",
            "Trilogia Raimi e MCU me filmaram.",
            "Miles Morales herdou mantos depois.",
            "Frase grande poder grande responsabilidade me define.",
            "Máscara esconde rosto jovem de estudante.",
            "Balanceio entre pontes de Nova York.",
            "Meu nome traduzido mistura homem e inseto de oito patas.",
        ],
    },
    {
        "answer": "DOM PEDRO II",
        "clues": [
            "Fui último imperador do Brasil.",
            "Subi trono criança depois de abdicação do pai.",
            "Reinei por quase cinco décadas no século 19.",
            "Abolição da escravratura veio no meu fim.",
            "Proclamação da República me depôs em 1889.",
            "Exilei-me na Europa até morrer.",
            "Barba branca e túnica escura em retrato.",
            "Patrono das ciências e das artes no império.",
            "Falava várias línguas clássicas e modernas.",
            "Viajei incógnito pelo país enorme.",
            "Filha Isabel assinou Lei Áurea como regente.",
            "Críticos me viram tardio; liberais me viram conservador.",
            "Nome completo Pedro de Alcântara João.",
            "Coroa simbólica hoje está em museu.",
            "Data quinze de novembro virou feriado republicano.",
            "Sou figura central do Império brasileiro.",
            "Meu título Dom indica nobreza antes do nome Pedro.",
        ],
    },
    {
        "answer": "LAMPIÃO",
        "clues": [
            "Fui cangaceiro mais famoso do sertão nordestino.",
            "Meu nome verdadeiro era Virgulino Ferreira.",
            "Liderava bando armado na caatinga.",
            "Chapéu de couro e cartucheira na foto.",
            "Maria Bonita foi companheira conhecida.",
            "Governo mandou volantes me caçar.",
            "Morto emboscada em 1938 com parte do bando.",
            "Cabeça exposta em praça assustou e fascinou.",
            "Cangaço misturava banditismo e revolta social.",
            "Sertão de Pernambuco e Alagoas era meu chão.",
            "Folclore canta meu nome até hoje.",
            "Filme e novela romanticizaram ou condenaram.",
            "Lanterna na testa originou apelido Lampião.",
            "República Velha me viu como problema.",
            "Sou símbolo de resistência ou violência, debate aberto.",
            "Foto sepia circula em livro de história.",
            "Meu apelido remete a luz que ilumina escuro.",
        ],
    },
]
