# Cards 25-48 for raw-pessoa.json rewrite
PART2 = [
    {
        "answer": "TAYLOR SWIFT",
        "clues": [
            "Sou cantora e compositora americana de country e pop.",
            "Nasci em Reading, Pennsylvania, em 1989.",
            "Comecei teen escrevendo sobre ex na escola.",
            "Álbum Fearless me levou ao Grammy cedo.",
            "Regravei discos como Taylor's Version por direitos.",
            "Eras Tour lotou estádio em vários continentes.",
            "Namoros famosos viram letra de música depois.",
            "Shake It Off e Blank Space dominaram rádio.",
            "Mudei de country pra pop sem perder fã.",
            "Swifties são meu exército de fãs organizado.",
            "Briguei publicamente com Kanye no VMA.",
            "Folklore e Evermore trouxeram indie na pandemia.",
            "Gato Meredith e Olivia aparecem no Instagram.",
            "Meu nome completo é Taylor Alison Swift.",
            "Indústria musical debate streaming por causa minha.",
            "Escrevo quase tudo que canto sozinha.",
            "Meu sobrenome também é sobrenome de pássaro rápido.",
        ],
    },
    {
        "answer": "IVETE SANGALO",
        "clues": [
            "Sou cantora baiana de axé e carnaval.",
            "Nasci em Juazeiro, no interior da Bahia.",
            "Subi trio elétrico no circuito de Salvador.",
            "Fui vocalista da Banda Eva antes do solo.",
            "Real Fantasy virou DVD histórico na arena.",
            "Apresento programas de domingo na TV aberta.",
            "Energia de palco me rendeu apelido de furacão.",
            "Cantei Festa e Sorte Grande em coro nacional.",
            "Casada com Daniel Cady, mãe de filhos.",
            "Lotou Maracanã com show solo de mulher.",
            "Sou embaixadora de turismo e cultura baiana.",
            "Bloco meu enche rua no verão de fevereiro.",
            "Já cantei com Gal Costa e outros ícones.",
            "Voz potente aguenta arena sem microfone fraco.",
            "Meu primeiro nome tem cinco letras e acento no E.",
            "Represento axé fora do Brasil em festival.",
            "Meu sobrenome tem sete letras e começa com S.",
        ],
    },
    {
        "answer": "RONALDINHO GAÚCHO",
        "clues": [
            "Sou meia brasileiro de sorriso e drible fácil.",
            "Nasci em Porto Alegre, apelido Gaúcho no sobrenome.",
            "Brilhei no Grêmio antes de ir pro PSG.",
            "No Barcelona, ganhei Bola de Ouro em 2005.",
            "Cobertura no canto contra Inglaterra marcou Copa 2002.",
            "Dança com a bola e elástico viraram meu cartão.",
            "Joguei no Milan, Flamengo e outros clubes depois.",
            "Camisa dez da seleção brilhou comigo no penta.",
            "Meu irmão Assis também foi jogador.",
            "Chuteiras douradas e bandana marcaram visual.",
            "No auge, anunciei refrigerante sorrindo de orelha a orelha.",
            "Fui preso por passaporte irregular na Paraguai, notícia recente.",
            "Muita gente me coloca como mais talentoso puro da geração.",
            "Apelido Ronaldinho diferencia do Ronaldo fenômeno.",
            "Treinei futsal de menino no Rio Grande do Sul.",
            "Hoje faço evento, redes e comentário esporádico.",
            "Meu apelido termina com inho e tem acento no U.",
        ],
    },
    {
        "answer": "MARÍLIA MENDONÇA",
        "clues": [
            "Sou cantora sertaneja que popularizou sofrência feminina.",
            "Nasci em Cristianópolis, Goiás, em 1994.",
            "Estourei com Infiel e composição honesta.",
            "Apelidaram meu estilo de feminejo ou sertanejo raiz.",
            "Gravei ao vivo com violão e sanfona na plateia.",
            "Letra falava de traição sem romantizar macho.",
            "Morri jovem em acidente de avião em 2021.",
            "Brasil chorou quando a notícia chegou.",
            "Posthumous releases continuaram chartando.",
            "Era mãe do Léo, filho que aparecia nas redes.",
            "Cabelo curto e estilo simples viraram referência.",
            "Colaborei com Maiara e Maraisa e outros duos.",
            "Show lotava ginásio em cidade pequena.",
            "Voz grave e emocionada era minha assinatura.",
            "Prêmio Multishow e outros marcaram carreira curta.",
            "Sou símbolo de mulher escrevendo hit de dor.",
            "Meu primeiro nome tem acento no I e sobrenome no O.",
        ],
    },
    {
        "answer": "WHINDERSSON NUNES",
        "clues": [
            "Sou comediante e youtuber do Piauí.",
            "Nasci em Bom Jesus, interior nordestino.",
            "Comecei vídeo de humor no quarto simples.",
            "Hoje tenho milhões inscritos no YouTube.",
            "Stand-up lota teatro pelo Brasil.",
            "Falo de pobreza, família e autoestima com riso.",
            "Cabelo colorido e barba marcaram fases.",
            "Atuei em filme e série depois da fama.",
            "Namoro e término vira matéria de fofoca.",
            "Gravei especial para streaming global.",
            "Sou um dos criadores brasileiros mais seguidos.",
            "Piada sobre mãe e infância dura enche plateia.",
            "Investi em cinema e produção própria.",
            "Sotaque piauiense é parte da minha marca.",
            "Já vendi ingresso esgotado em arena grande.",
            "Conteúdo mistura stand-up, vlog e música.",
            "Meu sobrenome tem cinco letras e acento no U.",
        ],
    },
    {
        "answer": "OS TRAPALHÕES",
        "clues": [
            "Somos quarteto de comédia física da TV brasileira.",
            "Nos reunimos nos anos 70 no programa do Silvio.",
            "Didi, Dedé, Mussum e Zacarias eram nossos apelidos.",
            "Carlos Alberto, Renato, Mussum e Zacarias formavam elenco.",
            "Gags de pancadaria leve enchem sábado à tarde.",
            "Filme de cinema lotou ingresso nas décadas 80.",
            "Frase Isso, isso, isso virou bordão nacional.",
            "Didi era o líder magro de gravata borboleta.",
            "Mussum falava com sotaque e comia feijão em sketch.",
            "Zacarias era baixinho e falava com voz aguda.",
            "Dedé era o mais novo e levava esporro.",
            "Perdemos integrantes e o grupo nunca foi igual.",
            "Humor físico estilo Chaplin nos inspirou.",
            "Reprises ainda passam em canal aberto.",
            "Geração inteira riu de queda e tapa na cara.",
            "Nome do grupo remete a equipe desastrada.",
            "Nosso nome plural tem acento no O e termina em es.",
        ],
    },
    {
        "answer": "PAULO COELHO",
        "clues": [
            "Sou escritor brasileiro mais traduzido do planeta.",
            "Nasci no Rio de Janeiro, em 1947.",
            "Lancei O Alquimista, bestseller global.",
            "Viajei de caminhão na juventude hippie.",
            "Fui compositor de letra de canção antes dos livros.",
            "Bruxaria e misticismo aparecem nas minhas tramas.",
            "Veronika Decide Morrer também virou filme.",
            "Posto reflexão diária nas redes para milhões.",
            "Acumulo Guinness por tradução de autor vivo.",
            "Critics me acham simples demais; leitores me adoram.",
            "Peregrinação a Santiago virou livro autobiográfico.",
            "Uso Twitter e Instagram com frase curta motivacional.",
            "Morei na Suíça e mantenho vida internacional.",
            "Editora Rocco publica quase tudo meu no Brasil.",
            "História de pastor e tesouro marcou minha carreira.",
            "Sou referência de autoajuda literária no mundo.",
            "Meu sobrenome tem seis letras e acento no E.",
        ],
    },
    {
        "answer": "OSCAR NIEMEYER",
        "clues": [
            "Sou arquiteto brasileiro de curva e concreto branco.",
            "Nasci no Rio, vivi mais de um século.",
            "Desenhei Brasília ao lado de Lúcio Costa.",
            "Congresso Nacional tem cúpula e prato meus.",
            "Catedral de Brasília parece coroa de espinhos.",
            "Edifício Copan curva o horizonte de São Paulo.",
            "Sede da ONU em Nova York tem minha mão.",
            "Comunista declarado, exilado na ditadura.",
            "Museu de Niterói flutua como disco na baía.",
            "Prêmio Pritzker reconheceu meu legado.",
            "Formas orgânicas imitam montanha e mulher.",
            "Trabalhei com Le Corbusier no começo.",
            "Desenhei até morto aos 104 anos.",
            "Curva sensual virou assinatura nacional.",
            "Pavilhão de Ibirapuera é obra minha em SP.",
            "Brasil exporta minha estética modernista.",
            "Meu primeiro nome tem cinco letras e acento no A.",
        ],
    },
    {
        "answer": "SANTOS DUMONT",
        "clues": [
            "Sou aviador brasileiro que voou antes da discórdia.",
            "Nasci em Palmira, hoje Santos Dumont MG.",
            "14 bis decolou no Campo de Bagatelle em 1906.",
            "Demoiselle foi avião leve que construí depois.",
            "Usei chapéu panamá e visual elegante.",
            "Moro em Paris quando invento voou moda.",
            "Relógio de pulso popularizei pra pilotar.",
            "Controverso duelo com irmãos Wright divide historiadores.",
            "Depressão me levou ao suicídio em Guarujá, 1932.",
            "Aeroporto e cidade levam meu nome no Brasil.",
            "Cartão postal do Cristo no Rio me homenageou.",
            "Nobre e filho de cafeicultor mineiro.",
            "Primeiro voo público europeu me consagrou.",
            "Hoje patrono da Aeronáutica brasileira.",
            "Bar no Rio onde jantava ainda é ponto turístico.",
            "Brasil e França disputam meu legado com orgulho.",
            "Meu sobrenome tem seis letras e repete a letra M.",
        ],
    },
    {
        "answer": "MACHADO DE ASSIS",
        "clues": [
            "Sou escritor brasileiro do século 19.",
            "Nasci mulato pobre no Rio imperial.",
            "Fundei e presidi a Academia Brasileira de Letras.",
            "Dom Casmurro deixa leitor duvidar de Capitu.",
            "Memórias Póstumas de Brás Cubas narro do além.",
            "Ironia fina corta classe média carioca.",
            "Trabalhei de tipógrafo e funcionário público.",
            "Esposa Carolina Joaquina me acompanhou a vida.",
            "Quincas Borba e Esaú e Jacó completam meu cânone.",
            "Meu estatuto na ABL ocupa cadeira fundadora.",
            "Realismo psicológico me coloca no topo do canon.",
            "Crítico social disfarçado de humor elegante.",
            "Morri em 1908, deixando obra central pro Brasil.",
            "Capa de livro me mostra bigode e terno escuro.",
            "Escola e biblioteca levam meu nome em todo país.",
            "Sou o Machado, não o outro Machado pintor.",
            "Meu sobrenome de Assis remete a cidade paulista.",
        ],
    },
    {
        "answer": "CARMEN MIRANDA",
        "clues": [
            "Sou cantora e atriz baiana que brilhou em Hollywood.",
            "Nasci em Marco de Canaveses, Portugal, cresci no Rio.",
            "Turbante de frutas virou meu cartão postal.",
            "Dancei chinelo no chão em musical americano.",
            "Hollywood me chamou de Brazilian Bombshell.",
            "Samba-lelê e Chica Chica Boom Chic entraram no repertório.",
            "Morri jovem de ataque cardíaco em 1955.",
            "Visual exagerado hoje divide entre cultura e estereótipo.",
            "Apareci com Betty Grable em filme da Fox.",
            "Sotaque cantado encantou e caricaturou ao mesmo tempo.",
            "Sou ícone de kitsch e camp no mundo pop.",
            "Estátua na orla do Rio me homenageia.",
            "Mãe foi costureira, pai barbeiro no Largo da Lapa.",
            "Platform sandal gigante era calçado meu.",
            "Biografia recente reavalia racismo da indústria.",
            "Frutas plásticas no chapéu pesavam kilos.",
            "Meu primeiro nome tem cinco letras e acento no E.",
        ],
    },
    {
        "answer": "TIM MAIA",
        "clues": [
            "Sou cantor carioca de soul e groove brasileiro.",
            "Nasci no Rio, cresci com gospel e rádio americana.",
            "Obesidade e voz rouca eram minha marca.",
            "Cantei Descobridor dos Sete Miais e Gostava Tanto de Você.",
            "Passei tempo nos EUA antes de estourar aqui.",
            "História com maconha e prisão apareceu na vida.",
            "Tenho vários filhos reconhecidos na mídia.",
            "Álbum Tim Maia Racional foi disco cult.",
            "Morri de infarto em 1998, aos 55.",
            "Influenciei funk, sambalanço e black music BR.",
            "Show ao vivo era improviso e briga com público.",
            "Bíceps tatuado e camisa aberta no palco.",
            "Documentário e filme contaram minha trajetória.",
            "Frases espirituosas e humor ácido nas entrevistas.",
            "Sou referência de soul nacional sincero.",
            "Meu nome artístico tem três letras no sobrenome.",
            "Meu primeiro nome remete a Timothy em inglês.",
        ],
    },
    {
        "answer": "ELIS REGINA",
        "clues": [
            "Sou cantora gaúcha de voz imensa e temperamento.",
            "Nasci em Porto Alegre, apelidada Pimentinha.",
            "Arrancava aplauso em Festivals da TV Record.",
            "Cantei Arrastão e Como Nossos Pais com força.",
            "Parceira de Tom Jobim e Milton Nascimento.",
            "Morri cedo, em 1982, aos 36 anos.",
            "Filha Maria Rita também virou cantora premiada.",
            "Drama pessoal e palco intenso marcaram minha vida.",
            "Show no Montreux ficou histórico em vídeo.",
            "Microfone era extensão do meu corpo.",
            "Briguei e beijei colega na mesma entrevista.",
            "Cabelo cacheado e vestido justo anos 70.",
            "MPB não fala de mim sem emoção.",
            "Morte por overdose misturada com remédio chocou país.",
            "Documentário recente reviveu minha lenda.",
            "Sou uma das maiores vozes que o Brasil ouviu.",
            "Meu nome de batismo Elis termina com S.",
        ],
    },
    {
        "answer": "CAETANO VELOSO",
        "clues": [
            "Sou cantor baiano da Tropicália e MPB.",
            "Nasci em Santo Amaro da Purificação.",
            "Irmão Gil e eu movemos cultura nos anos 60.",
            "Exilado na Inglaterra durante a ditadura.",
            "Cantei Alegria Alegria e Tropicália.",
            "Letra poética mistura política e amor.",
            "Cabelo branco e voz suave marcam hoje.",
            "Filho Moreno também é músico e produtor.",
            "Prêmio Grammy latino e Oscar de trilha.",
            "Crítico de Bolsonaro em artigo e palco.",
            "So Pretty e Soirê são hits de diferentes fases.",
            "Escrevo livro e ensaio além de disco.",
            "Show acústico lota teatro mundo afora.",
            "Parceiro de Gal Costa por décadas.",
            "Sou referência intelectual pop no Brasil.",
            "Meu sobrenome tem seis letras e acento no O.",
            "Meu primeiro nome tem seis letras e acento no A.",
        ],
    },
    {
        "answer": "ZICO",
        "clues": [
            "Sou meia carioca apelidado de Galinho de Quintal.",
            "Nasci em Quintino, zona norte do Rio.",
            "Joguei a vida quase toda no Flamengo.",
            "Cobrança de falta com pouca corrida era minha.",
            "Artilheiro da seleção antes de Ronaldo fenômeno.",
            "Copa 82 ficou na saudade; 86 também.",
            "Fui para o futebol japonês depois do auge.",
            "Número dez da camisa rubro-negra me pertenceu.",
            "Treinei seleção e clubes com resultado misto.",
            "Comentarista de TV fala com franqueza.",
            "Gol de falta contra Liverpool ficou clássico.",
            "Meu nome real é Arthur Antunes Coimbra.",
            "Fundei clube e projeto social no Rio.",
            "Muita gente me chama de maior ídolo do Fla.",
            "Baixinho, branco, cabelo ralo na memória.",
            "Hoje sou referência técnica em debate esportivo.",
            "Meu apelido tem quatro letras e acento no I.",
        ],
    },
    {
        "answer": "ROMÁRIO",
        "clues": [
            "Sou atacante carioca de faro de gol.",
            "Nasci em Rio de Janeiro, joguei no Vasco.",
            "Artilheiro da Copa de 1994 nos EUA.",
            "Baixinho, driblava dentro da área pequena.",
            "Apelido Baixinho me acompanha até hoje.",
            "Passei por Barcelona, Flamengo e PSV.",
            "Milésimo gol virou festa nacional.",
            "Entrei na política como senador e prefeito.",
            "Falo sem filtro na TV e nas redes.",
            "Parceria com Bebeto virou dancinha de bebê na Copa.",
            "Confronto com Pelé deu manchete por gerações.",
            "Hoje comento e provoco no futebol.",
            "Camisa 11 marcou minha era no Vasco.",
            "Sou um dos maiores artilheiros da história.",
            "Estilo preguiçoso mentiroso: só aparecia pra gol.",
            "Meu nome tem acento no A e termina com O.",
            "Meu apelido de baixinho rima com anão carinhoso.",
        ],
    },
    {
        "answer": "GARRINCHA",
        "clues": [
            "Sou ponta brasileiro de perna torta e céu aberto.",
            "Nasci em Pau Grande, Rio de Janeiro.",
            "Copa de 58 e 62 brilharam com meus pés.",
            "Driblava zagueiro duas vezes por brincadeira.",
            "Joelho valgo não me impediu de ser gênio.",
            "Apelido de passarinho veio da infância.",
            "Nome completo Manoel Francisco dos Santos.",
            "Vida boêmia depois do apogeu me custou caro.",
            "Morri pobre em 1983, com 49 anos.",
            "Estádio Mané Garrincha em Brasília leva meu apelido.",
            "Pelé dizia que eu era o melhor de todos.",
            "Copa 62 na Chile foi meu espetáculo solo.",
            "Alcoolismo apareceu em biografia dura.",
            "Filha e família ainda falam de mim com orgulho.",
            "Sou símbolo de alegria pura no futebol.",
            "Pernas diferentes medidas confundiam marcador.",
            "Meu apelido tem oito letras e acento no A.",
        ],
    },
    {
        "answer": "PRINCESA ISABEL",
        "clues": [
            "Fui filha do imperador Pedro Segundo.",
            "Regente do Império quando meu pai viajava.",
            "Assinei lei que libertou escravos em 1888.",
            "Lei Áurea leva meu nome na história escolar.",
            "Apelidada de Redentora na época.",
            "Casei com conde d'Eu, príncipe francês.",
            "Vivi exílio após a Proclamação da República.",
            "Morri na França, longe do trono brasileiro.",
            "Retrato me mostra vestido branco e colar.",
            "Debates hoje questionam alcance real da abolição.",
            "Não liberei terra nem reparação aos libertos.",
            "Cidade no Rio leva meu nome em bairro nobre.",
            "Sou figura central do fim da escravidão legal.",
            "Imperatriz que nunca cheguei a ser oficialmente.",
            "Educada para ser consorte, acabei governando.",
            "Data treze de maio virou feriado em alguns lugares.",
            "Meu título começa com P e termina com A.",
        ],
    },
    {
        "answer": "ZUMBI DOS PALMARES",
        "clues": [
            "Fui líder de quilombo no século 17.",
            "Comandei Palmares, refúgio de escravizados fugidos.",
            "Nasci livre ou capturado, relatos divergem.",
            "Decapitação de minha cabeça foi troféu colonial.",
            "Dia vinte de novembro lembra minha resistência.",
            "Quilombo durou décadas contra bandeirantes.",
            "Mulher Dandara também liderou ao meu lado.",
            "Símbolo de liberdade negra no Brasil.",
            "Estátua e nome de rua me homenageiam.",
            "Luta não terminou com minha morte em 1695.",
            "Alagoas guarda memória do Quilombo dos Palmares.",
            "Feriado nacional discutido leva minha data.",
            "História mistura mito e documento escasso.",
            "Sou herói afro-brasileiro nas escolas.",
            "Nome Zumbi veio de língua africana, dizem.",
            "Filme e novela já contaram minha saga.",
            "Meu apelido tem cinco letras e acento no I.",
        ],
    },
    {
        "answer": "TARSILA DO AMARAL",
        "clues": [
            "Sou pintora modernista de São Paulo.",
            "Nasci em Capivari, interior paulista.",
            "Estudei em Paris com André Lhote.",
            "Abaporu virou ícone na capa de manifesto.",
            "Antropofagia cultural nasceu perto de mim.",
            "Oswald de Andrade foi meu marido e parceiro.",
            "Cores vivas e formas grandes marcam telas.",
            "Operária e A Negra falam de Brasil real.",
            "Retrospectiva lotou MASP em século 21.",
            "Sou uma das maiores artistas visuais do país.",
            "Família cafeicultora bancou minha formação.",
            "Paisagem de fábrica e morro entram no meu olhar.",
            "Gravura e desenho também fazem parte da obra.",
            "Morri em 1973, deixando acervo nacional.",
            "Cartão postal vende reprodução do Abaporu.",
            "Meu nome artístico usa só o primeiro nome feminino.",
            "Meu sobrenome tem três palavras e acento no A.",
        ],
    },
    {
        "answer": "HEBE CAMARGO",
        "clues": [
            "Sou apresentadora paulista de domingo na TV.",
            "Nasci em Santo Anastácio, interior de SP.",
            "Comandei Domingão da Hebe por décadas.",
            "Entrevistei político, artista e anônimo no sofá.",
            "Peruca loira e óculos grossos viraram marca.",
            "Opinião conservadora gerava polêmica e audiência.",
            "Comecei rádio antes de ir pra telinha.",
            "Filho Marcelo Camargo seguiu na comunicação.",
            "Faleci em 2012, aos 83, de infarto.",
            "Plateia ao vivo aplaudia minhas piadas prontas.",
            "Era mulher forte em TV quando homem dominava.",
            "Entrevista com Silvio Santos virou clássico.",
            "Bordão e risada própria abriam o programa.",
            "Crítica a rock e modernidade era meu estilo.",
            "Homenagem póstuma passou na Globo.",
            "Sou referência de domingo pre-internet.",
            "Meu primeiro nome tem quatro letras e acento no E.",
        ],
    },
    {
        "answer": "PADRE CÍCERO",
        "clues": [
            "Sou sacerdote cearense venerado como santo popular.",
            "Nasci em Juazeiro do Norte, em 1844.",
            "Milagres e multitudes me cercaram na vida.",
            "Romaria de setembro enche minha cidade natal.",
            "Estátua gigante minha domina o horizonte.",
            "Política local se misturou com minha influência.",
            "Igreja me beatificou no coração do povo, não no Vaticano.",
            "Críticos me viram charlatão; fiéis me viram salvador.",
            "Morri em 1934, deixando legião de devotos.",
            "Chapéu preto e barba branca em foto antiga.",
            "Nordeste inteiro conhece meu nome.",
            "Venda de souvenir com meu rosto é indústria.",
            "História de cruz sangrando fundou mito.",
            "Governadores negociavam comigo eleitoralmente.",
            "Sou símbolo de fé popular brasileira.",
            "Filme e telenovela já dramatizaram minha vida.",
            "Meu título religioso tem cinco letras e acento no I.",
        ],
    },
    {
        "answer": "LUDMILLA",
        "clues": [
            "Sou cantora carioca de funk e pop.",
            "Nasci em Duque de Caxias, baixada fluminense.",
            "Comecei no funk com nome MC Beyoncé.",
            "Hit Fala Mal de Mim estourou baile e rádio.",
            "Casei com dancer Brunna Gonçalves.",
            "Cabelo vermelho e tatuagem marcam visual.",
            "Cantei com Anitta e outros nomes grandes.",
            "Álbum Numanice misturou pagode e funk.",
            "Sou referência LGBTQ+ visível na música.",
            "Reality e documentário contaram minha história.",
            "Voz potente aguenta feat internacional.",
            "Transição de MC para Ludmilla foi rebranding.",
            "Show de carnaval lota bloco no Rio.",
            "Letra fala de empoderamento e baile.",
            "Grammy latino e prêmio nacional marcaram.",
            "Meu nome artístico tem oito letras e acento no A.",
            "Meu nome lembra imperatriz russa, só que com L.",
        ],
    },
    {
        "answer": "FAUSTÃO",
        "clues": [
            "Sou apresentador de domingo e auditório na Globo.",
            "Nome artístico vem de Fausto, comão carinhoso.",
            "Domingão comigo durou mais de trinta anos.",
            "Sorteio de carro e moto emocionava plateia.",
            "Entrevistei celebridade sentado no sofá amarelo.",
            "Frase olha a câmera três virou meme.",
            "Transplante de coração marcou minha saúde recente.",
            "Saí da Globo e fui pra Record em nova fase.",
            "Barriga e terno claro eram meu visual.",
            "Quadro de dança do ventre e humor light encheram.",
            "Comecei rádio em Ribeirão Preto.",
            "Nome completo Fausto Silva.",
            "Audiência de domingo disputava com Silvio.",
            "Música ao vivo abria programa toda semana.",
            "Hoje também apresento quadro de saúde.",
            "Sou voz de sábado à noite pra família.",
            "Meu apelido tem sete letras e acento no Ã.",
        ],
    },
]
